const wordMaster = [
  { meaning: "충고하다", word: "advise" },
  { meaning: "능력", word: "ability" },
  { meaning: "총계, 양, 총계가 ~되다", word: "amount" },
  { meaning: "이용 가능한, 쓸모 있는", word: "available" },
  { meaning: "태도, 입장", word: "attitude" },
  { meaning: "평균, 평균의", word: "average" },
  { meaning: "청중, 관객", word: "audience" },
  { meaning: "편안, 위로,  편안하게 하다", word: "comfort" },
  { meaning: "(예의바르게) 행동하다", word: "behave" },
  { meaning: "소비하다", word: "consume" },
  { meaning: "개발하다, 발달하다", word: "develop" },
  { meaning: "함유하다, 포함하다", word: "contain" },
  { meaning: "고용하다", word: "employ" },
  { meaning: "결심하다, 결정하다", word: "determine" },
  { meaning: "향상시키다, 향상하다", word: "improve" },
  { meaning: "촉구하다, 격려하다", word: "encourage" },
  { meaning: "개인, 개인의, 개인적인", word: "individual" },
  { meaning: "비용, 지출", word: "expense" },
  { meaning: "영향, 영향을 끼치다", word: "influence" },
  { meaning: "~에게 깊은 인상을 주다", word: "impress" },
  { meaning: "알리다, 통지하다", word: "inform" },
  { meaning: "포함하다, 말려들게 하다", word: "involve" },
  { meaning: "국제의, 국제적인", word: "international" },
  { meaning: "지방의, 지역의, 장소의", word: "local" },
  { meaning: "공급하다, 준비하다", word: "provide" },
  { meaning: "재료, 물질, 물질의", word: "material" },
  { meaning: "관계", word: "relationship" },
  { meaning: "물체, 목표, 반대하다", word: "object" },
  { meaning: "필요로 하다, 요구하다", word: "require" },
  { meaning: "기회", word: "opportunity" },
  { meaning: "연구, 연구하다,  조사하다", word: "research" },
  { meaning: "긍정적인", word: "positive" },
  { meaning: "봉사, 공공업무, 서비스", word: "service" },
  { meaning: "인지하다, 인정하다", word: "recognize" },
  { meaning: "사회의, 사교적인", word: "social" },
  { meaning: "(탈 것을) 타다, 태움", word: "ride" },
  { meaning: "무서운, 끔찍한", word: "terrible" },
  { meaning: "강조, 강조하다,  스트레스", word: "stress" },
  { meaning: "자원봉사, 지원자 자발적으로 ~하다", word: "volunteer" },
  { meaning: "그러므로, 그 결과", word: "therefore" },
  { meaning: "~에 영향을 미치다, ~인체 하다", word: "affect" },
  { meaning: "접근하다, 접근", word: "approach" },
  { meaning: "놀라게 하다", word: "amaze" },
  { meaning: "인지하는, 알고 있는", word: "aware" },
  { meaning: "이익, 이익이 되다", word: "benefit" },
  { meaning: "배경, 배경지식, 이유", word: "background" },
  { meaning: "세포", word: "cell" },
  { meaning: "직업, 경력", word: "career" },
  { meaning: "화학", word: "chemistry" },
  { meaning: "복잡한, 복합체", word: "complex" },
  { meaning: "결심하다, 결정하다", word: "decide" },
  { meaning: "접촉, 접촉하다", word: "contact" },
  { meaning: "수요, 요구하다", word: "demand" },
  { meaning: "정의하다, 한계를 짓다", word: "define" },
  { meaning: "발견하다", word: "discover" },
  { meaning: "~에도 불구하고", word: "despite" },
  { meaning: "경제의, 경제학의", word: "economic" },
  { meaning: "세부, 상세한, 상술하다", word: "detail" },
  { meaning: "감정", word: "emotion" },
  { meaning: "사라지다", word: "disappear" },
  { meaning: "(사물의) 본질, 정수", word: "essence" },
  { meaning: "결국", word: "eventually" },
  { meaning: "집중하다, 초점", word: "focus" },
  { meaning: "유행, 방식, 만들어 내다", word: "fashion" },
  { meaning: "직접의, 즉각적인", word: "immediate" },
  { meaning: "일으키다, 발생시키다", word: "generate" },
  { meaning: "논란거리, 발행하다", word: "issue" },
  { meaning: "소설, 참신한", word: "novel" },
  { meaning: "수준, 수평, 수평의 평탄하게 만들다", word: "level" },
  { meaning: "꾸러미, 포장, 포장하다", word: "package" },
  { meaning: "(사건이) 일어나다,  발생하다", word: "occur" },
  { meaning: "참여하다, 참가하다", word: "participate" },
  { meaning: "직업", word: "profession" },
  { meaning: "공연, 성적, 성과", word: "performance" },
  { meaning: "적절한, 알맞은", word: "proper" },
  { meaning: "자랑스러워하는,  자만하는", word: "proud" },
  { meaning: "줄이다, 낮추다", word: "reduce" },
  { meaning: "안전한, 확보하다", word: "secure" },
  { meaning: "따라서", word: "thus" },
  { meaning: "해결, 해결책", word: "solution" },
  { meaning: "계좌, 이야기, 설명하다", word: "account" },
  { meaning: "활동적인, 적극적인", word: "active" },
  { meaning: "균형, 균형을 이루다", word: "balance" },
  { meaning: "운동의, 운동 경기의", word: "athletic" },
  { meaning: "생물학", word: "biology" },
  { meaning: "~의 원인이 되다, 원인", word: "cause" },
  { meaning: "탄생", word: "birth" },
  { meaning: "일정한, 불면의", word: "constant" },
  { meaning: "구성하다, 작문하다", word: "compose" },
  { meaning: "치아의", word: "dental" },
  { meaning: "축하하다", word: "congratulate" },
  { meaning: "교환하다", word: "exchange" },
  { meaning: "감소, 감소하다", word: "decrease" },
  { meaning: "연장하다, 넓히다", word: "extend" },
  { meaning: "묘사하다, 표현하다", word: "describe" },
  { meaning: "극단, 극단의", word: "extreme" },
  { meaning: "바라다, 욕망, 욕구", word: "desire" },
  { meaning: "요인, 요소", word: "factor" },
  { meaning: "만기의, ~하기로 돼 있는", word: "due" },
  { meaning: "빈번한, ~종종 방문하다", word: "frequent" },
  { meaning: "장치, 장비", word: "equipment" },
  { meaning: "천재", word: "genius" },
  { meaning: "전문가", word: "expert" },
  { meaning: "서식지, 주거지", word: "habitat" },
  { meaning: "~의 뒤를 잇다,  따라가다", word: "follow" },
  { meaning: "주장하다", word: "insist" },
  { meaning: "부정적인", word: "negative" },
  { meaning: "외로운", word: "lonely" },
  { meaning: "경우, 특별한 일", word: "occasion" },
  { meaning: "정신의", word: "mental" },
  { meaning: "발표하다, 출판하다", word: "publish" },
  { meaning: "정치, 정치학", word: "politics" },
  { meaning: "재활용하다", word: "recycle" },
  { meaning: "반영하다, 숙고하다", word: "reflect" },
  { meaning: "경감하다, 안도시키다", word: "relieve" },
  { meaning: "(생물 분류상의) 종", word: "species" },
  { meaning: "대체하다", word: "replace" },
  { meaning: "안정된, 한결같은", word: "steady" },
  { meaning: "기간, 학기, 용어, 조건", word: "term" },
  { meaning: "~하는 경향이 있다,  돌보다", word: "tend" },
  { meaning: "접근, 이용", word: "access" },
  { meaning: "동반하다", word: "accompany" },
  { meaning: "허락하다, 인정하다", word: "allow" },
  { meaning: "사과하다", word: "apologize" },
  { meaning: "발표하다, 알리다", word: "announce" },
  { meaning: "능력이 있는", word: "capable" },
  { meaning: "천문학", word: "astronomy" },
  { meaning: "결합하다, 겸하다", word: "combine" },
  { meaning: "집중하다", word: "concentrate" },
  { meaning: "상업, 교역", word: "commerce" },
  { meaning: "자신이 있는", word: "confident" },
  { meaning: "건설하다", word: "construct" },
  { meaning: "기쁨, 기쁘게 하다", word: "delight" },
  { meaning: "점점 줄어들다, 저하되다", word: "dwindle" },
  { meaning: "무능력의, 장애의", word: "disabled" },
  { meaning: "즐겁게 하다", word: "entertain" },
  { meaning: "전기", word: "electricity" },
  { meaning: "좌절 시키다", word: "frustrate" },
  { meaning: "강조하다", word: "emphasize" },
  { meaning: "연료, 연료를 가하다", word: "fuel" },
  { meaning: "확고한, 단단한, 회사", word: "firm" },
  { meaning: "유전자", word: "gene" },
  { meaning: "홍수, 범람 시키다", word: "flood" },
  { meaning: "(수량이) 늘다,  증가, 이자", word: "increase" },
  { meaning: "점차, 차츰", word: "gradually" },
  { meaning: "제조, 제품, 제조하다", word: "manufacture" },
  { meaning: "상처를 입히다", word: "injure" },
  { meaning: "움직임, 운동", word: "movement" },
  { meaning: "부족, ~이 부족하다", word: "lack" },
  { meaning: "예언하다", word: "predict" },
  { meaning: "허락하다, 인정하다", word: "permit" },
  { meaning: "압력, 압력을 가하다", word: "pressure" },
  { meaning: "그림자, 그늘지게 하다", word: "shadow" },
  { meaning: "양", word: "quantity" },
  { meaning: "의미하다, 중요하다", word: "signify" },
  { meaning: "응답, 반응", word: "response" },
  { meaning: "위협, 협박", word: "threat" },
  { meaning: "시야, 광경, 시력", word: "sight" },
  { meaning: "바꾸다, 변하다", word: "vary" },
  { meaning: "희생, 희생자", word: "victim" },
  { meaning: "흡수하다, 열중 시키다", word: "absorb" },
  { meaning: "도움을 주다", word: "assist" },
  { meaning: "이익, 유리한 점", word: "advantage" },
  { meaning: "요구, 주장, 주장하다", word: "claim" },
  { meaning: "분석하다", word: "analyze" },
  { meaning: "확신시키다", word: "convince" },
  { meaning: "추정하다, 태도를 취하다", word: "assume" },
  { meaning: "생물, 피조물", word: "creature" },
  { meaning: "시도하다, 시도", word: "attempt" },
  { meaning: "비난하다", word: "criticize" },
  { meaning: "결론짓다, 끝내다", word: "conclude" },
  { meaning: "재해, 재앙, 재앙의", word: "disaster" },
  { meaning: "혼동하다, 혼란 시키다", word: "confuse" },
  { meaning: "할인, 할인하다", word: "discount" },
  { meaning: "기부하다", word: "donate" },
  { meaning: "효율적인, 유능한", word: "efficient" },
  { meaning: "전자의", word: "electronic" },
  { meaning: "설립하다, 재정하다", word: "establish" },
  { meaning: "당황한", word: "embarrassed" },
  { meaning: "특징, ~를 특징으로 하다, 특집기사, 생김새", word: "feature" },
  { meaning: "가능하게 하다", word: "enable" },
  { meaning: "치료하다, 낫게 하다", word: "heal" },
  { meaning: "(믿기 어려울 만큼)  굉장한", word: "incredible" },
  { meaning: "방해하다, 중단하다", word: "interrupt" },
  { meaning: "지적하다, 나타내다", word: "indicate" },
  { meaning: "얻다, 획득하다", word: "obtain" },
  { meaning: "지시, 제품 사용 설명서", word: "instruction" },
  { meaning: "논리적인,  분별력이 있는", word: "reasonable" },
  { meaning: "노동, 노동하다", word: "labor" },
  { meaning: "거주자", word: "resident" },
  { meaning: "도덕적인", word: "moral" },
  { meaning: "혁명, 갑작스런 변화", word: "revolution" },
  { meaning: "개성, 성격, 특색", word: "personality" },
  { meaning: "재고품, 저장, 저장하다", word: "stock" },
  { meaning: "의견, 의견을 말하다, 주목, ~에 주목하다", word: "remark" },
  { meaning: "낯선 사람, 문외한", word: "stranger" },
  { meaning: "노력하다, 노력, 투쟁", word: "struggle" },
  { meaning: "굉장한", word: "terrific" },
  { meaning: "다양성, 다양", word: "variety" },
  { meaning: "조수", word: "tide" },
  { meaning: "놀람, 경보", word: "alarm" },
  { meaning: "습득하다", word: "acquire" },
  { meaning: "암, 악성 종양", word: "cancer" },
  { meaning: "간단한, 간단히 알리다, 짧은 보고", word: "brief" },
  { meaning: "실마리, 단서", word: "clue" },
  { meaning: "양심", word: "conscience" },
  { meaning: "우울하게 하다,  낙담 시키다", word: "depress" },
  { meaning: "숙고하다, 고려하다", word: "consider" },
  { meaning: "~받을 가치가 있다,  ~할 만하다", word: "deserve" },
  { meaning: "10년, 10년의", word: "decade" },
  { meaning: "가장자리", word: "edge" },
  { meaning: "곡물,  낟알", word: "grain" },
  { meaning: "나이가 위인, 연장자", word: "elder" },
  { meaning: "상호작용하다", word: "interact" },
  { meaning: "관여하다, 약속하다, 약혼하다", word: "engage" },
  { meaning: "길이", word: "length" },
  { meaning: "매혹하다, 마음을 빼앗다", word: "fascinate" },
  { meaning: "평생, 평생의", word: "lifetime" },
  { meaning: "수입하다, 수입, 뜻하다", word: "import" },
  { meaning: "의미심장한", word: "meaningful" },
  { meaning: "독립적인", word: "independent" },
  { meaning: "(시간, 장소를) 차지하다, 전념하다", word: "occupy" },
  { meaning: "동기부여하다", word: "motivate" },
  { meaning: "열정", word: "passion" },
  { meaning: "자격을 얻다", word: "qualify" },
  { meaning: "시, 운문", word: "poetry" },
  { meaning: "반응하다, 반작용하다", word: "react" },
  { meaning: "자세, 자세를 취하다,  ~인 체하다, 제출하다", word: "pose" },
  { meaning: "상기, 상기하다", word: "recall" },
  { meaning: "심리, 심리학", word: "psychology" },
  { meaning: "위험, 위험을 감수하다", word: "risk" },
  { meaning: "구매, 구매하다", word: "purchase" },
  { meaning: "구체적인", word: "specific" },
  { meaning: "길, 항로, 경로", word: "route" },
  { meaning: "이론", word: "theory" },
  { meaning: "급료, 봉급", word: "salary" },
  { meaning: "취급, 대우, 치료법", word: "treatment" },
  { meaning: "심한, 엄한", word: "severe" },
  { meaning: "난폭한, 폭력적인", word: "violent" },
  { meaning: "잡초, 잡초를 제거하다", word: "weed" },
  { meaning: "찬성하다, 승인하다", word: "approve" },
  { meaning: "정확한", word: "accurate" },
  { meaning: "끔찍한, 지독한", word: "awful" },
  { meaning: "정리하다, 준비하다", word: "arrange" },
  { meaning: "논평, 논평하다", word: "comment" },
  { meaning: "붙이다, 첨부하다", word: "attach" },
  { meaning: "범죄", word: "crime" },
  { meaning: "위원회", word: "committee" },
  { meaning: "전시, 전시하다,  나타내다", word: "display" },
  { meaning: "상담하다, 참고하다", word: "consult" },
  { meaning: "고갈된, 기운이 다 빠진", word: "exhausted" },
  { meaning: "국내의, 가정의, 내부의", word: "domestic" },
  { meaning: "재정, 재무,  자금을 조달하다", word: "finance" },
  { meaning: "도심, 도심의", word: "downtown" },
  { meaning: "유행성 감기", word: "flu" },
  { meaning: "초보의, 기초적인", word: "elementary" },
  { meaning: "뛰다, 도약하다, 도약", word: "leap" },
  { meaning: "엄청난, 거대한, 대단한", word: "enormous" },
  { meaning: "기계공", word: "mechanic" },
  { meaning: "~을 제외하고, 제외하다", word: "except" },
  { meaning: "단지, ~에 불과한", word: "mere" },
  { meaning: "시설, 편의, 재능", word: "facility" },
  { meaning: "기분, 분위기", word: "mood" },
  { meaning: "격차, 틈", word: "gap" },
  { meaning: "작업, 운영, 수술", word: "operation" },
  { meaning: "여행", word: "journey" },
  { meaning: "정책, 수단, 방법", word: "policy" },
  { meaning: "덩어리", word: "mass" },
  { meaning: "시골의", word: "rural" },
  { meaning: "괴물, 도깨비", word: "monster" },
  { meaning: "연속, 시리즈물", word: "series" },
  { meaning: "명백한, 평범한", word: "plain" },
  { meaning: "둘러싸다", word: "surround" },
  { meaning: "회복하다, 되찾다", word: "recover" },
  { meaning: "설문조사, 조사하다,  둘러보다", word: "survey" },
  { meaning: "언급하다, 위탁하다", word: "refer" },
  { meaning: "생존", word: "survival" },
  { meaning: "보수, 보답하다", word: "reward" },
  { meaning: "전형적인, 대표적인", word: "typical" },
  { meaning: "부(富), 재산", word: "wealth" },
  { meaning: "인정하다", word: "admit" },
  { meaning: "이루다, 성취하다", word: "accomplish" },
  { meaning: "찢다, 고장을 내다", word: "break" },
  { meaning: "채택하다, 입양하다", word: "adopt" },
  { meaning: "낳다, 양육하다", word: "breed" },
  { meaning: "관점, 양성, 면", word: "aspect" },
  { meaning: "연기하다, 미루다", word: "delay" },
  { meaning: "대기, 분위기", word: "atmosphere" },
  { meaning: "장치, 고안, 방책", word: "device" },
  { meaning: "수여하다, 상", word: "award" },
  { meaning: "윤리", word: "ethic" },
  { meaning: "문명", word: "civilization" },
  { meaning: "서류철, 서류철을  작성하다, 제출하다", word: "file" },
  { meaning: "결과, 중요성", word: "consequence" },
  { meaning: "포함하다", word: "include" },
  { meaning: "장식하다", word: "decorate" },
  { meaning: "즉각적인, 즉석의", word: "instant" },
  { meaning: "두통", word: "headache" },
  { meaning: "여가, 자유시간, 한가한", word: "leisure" },
  { meaning: "수평선, 지평선", word: "horizon" },
  { meaning: "근육, 힘, 강제", word: "muscle" },
  { meaning: "~할 작정이다, 의도하다", word: "intend" },
  { meaning: "빚지고 있다,  (명예 등을)~에 돌리다", word: "owe" },
  { meaning: "꼬리표, ~를…라고 부르다, 라벨을 붙이다", word: "label" },
  { meaning: "앞의, 이전의", word: "previous" },
  { meaning: "잠재적인, 잠재력", word: "potential" },
  { meaning: "생산하다, 제조하다", word: "produce" },
  { meaning: "보존하다, 보호하다", word: "preserve" },
  { meaning: "여전히~이다, 남다,  남은 것", word: "remain" },
  { meaning: "열, 줄, 말다툼, 노를 젓다", word: "row" },
  { meaning: "드러내다, 폭로하다", word: "reveal" },
  { meaning: "미끄러지다, 실수하다", word: "slip" },
  { meaning: "약간의, 경미한", word: "slight" },
  { meaning: "파도, 파도타기를 하다", word: "surf" },
  { meaning: "가정하다, 추측하다", word: "suppose" },
  { meaning: "목표, 목표로 삼다", word: "target" },
  { meaning: "도시의", word: "urban" },
  { meaning: "지하의, 지하", word: "underground" },
  { meaning: "증인, 증거, 목격하다", word: "witness" },
  { meaning: "~이 아닌 한, 만약 ~이 아니라면", word: "unless" },
  { meaning: "중독 시키다", word: "addict" },
  { meaning: "적용, 신청", word: "application" },
  { meaning: "인공적인, 인조의", word: "artificial" },
  { meaning: "협력하다", word: "cooperate" },
  { meaning: "자동적인, 기계적인", word: "automatic" },
  { meaning: "비상사태", word: "emergency" },
  { meaning: "기초, 원리", word: "basis" },
  { meaning: "(빛, 열 등을) 방출하다", word: "emit" },
  { meaning: "다르다, 의견을 달리하다", word: "differ" },
  { meaning: "평가하다", word: "evaluate" },
  { meaning: "실망시키다", word: "disappoint" },
  { meaning: "달성하다, 이행하다", word: "fulfill" },
  { meaning: "(우연히)만나다, 마주침", word: "encounter" },
  { meaning: "승인하다, 수여하다", word: "grant" },
  { meaning: "명백한", word: "evident" },
  { meaning: "보증하다, 보증", word: "guarantee" },
  { meaning: "~임을 확인하다,  식별하다, 동일시하다", word: "identify" },
  { meaning: "충격, 영향, 충격을 주다", word: "impact" },
  { meaning: "기억하다", word: "memorize" },
  { meaning: "영원한, 영구적인", word: "permanent" },
  { meaning: "소유하다,  ~의 마음을 사로잡다", word: "possess" },
  { meaning: "물리학", word: "physics" },
  { meaning: "원칙, 원리", word: "principle" },
  { meaning: "철도, 선로", word: "railroad" },
  { meaning: "현실적인, 현실주의의", word: "realistic" },
  { meaning: "의지하다", word: "rely" },
  { meaning: "지역", word: "region" },
  { meaning: "요청, 요청하다", word: "request" },
  { meaning: "오르다, 일어나다 오름, 상승", word: "rise" },
  { meaning: "저항하다", word: "resist" },
  { meaning: "규모, 저울, 비늘", word: "scale" },
  { meaning: "제거하다", word: "rid" },
  { meaning: "비서, 서기관, 장관", word: "secretary" },
  { meaning: "역겹다, 악취가 나다", word: "stink" },
  { meaning: "좀처럼~않는", word: "seldom" },
  { meaning: "주제, 화제, 논제", word: "theme" },
  { meaning: "기준, 표준, 기준의", word: "standard" },
  { meaning: "굉장한, 무시무시한", word: "tremendous" },
  { meaning: "물질, 본질, 실체", word: "substance" },
  { meaning: "투표, 투표하다", word: "vote" },
  { meaning: "모험", word: "adventure" },
  { meaning: "장비, 기어, 맞게하다 조정하다", word: "gear" },
  { meaning: "괴롭히다, 귀찮게 하다", word: "annoy" },
  { meaning: "대안, 대안의", word: "alternative" },
  { meaning: "(통나무) 오두막집, 객실 선실", word: "cabin" },
  { meaning: "간청하다, 호소하다,  항의, 항의하다", word: "appeal" },
  { meaning: "상황, 환경", word: "circumstance" },
  { meaning: "권위, 당국", word: "authority" },
  { meaning: "곡선, 곡선길,  속임수, 사기", word: "curve" },
  { meaning: "서명, 서명하다", word: "autograph" },
  { meaning: "분배하다", word: "distribute" },
  { meaning: "회사의, 법인의", word: "corporate" },
  { meaning: "입장, 입구, 입학", word: "entrance" },
  { meaning: "부러워하다, 부러움", word: "envy" },
  { meaning: "평가하다", word: "estimate" },
  { meaning: "모의다", word: "gather" },
  { meaning: "겁먹게하다", word: "frighten" },
  { meaning: "해치다, 손해, 손상", word: "harm" },
  { meaning: "주저하다, 망설이다", word: "hesitate" },
  { meaning: "동일한, 일란성의", word: "identical" },
  { meaning: "통역하다", word: "interpret" },
  { meaning: "순결, 청정", word: "innocence" },
  { meaning: "장소, 위치", word: "location" },
  { meaning: "투자", word: "investment" },
  { meaning: "유기체, 생물, 생명체", word: "organism" },
  { meaning: "제공하다, 제안하다", word: "offer" },
  { meaning: "설득하다", word: "persuade" },
  { meaning: "인지하다, 인식하다", word: "perceive" },
  { meaning: "(열대)우림", word: "rainforest" },
  { meaning: "등급, 등급을 매기다", word: "rank" },
  { meaning: "암송하다", word: "recite" },
  { meaning: "광선", word: "ray" },
  { meaning: "거절하다", word: "refuse" },
  { meaning: "놓아주다, 발표하다 석방, 발표,", word: "release" },
  { meaning: "결심하다, 결심 시키다,  분해하다, 해결하다", word: "resolve" },
  { meaning: "은퇴하다", word: "retire" },
  { meaning: "제한하다, 한정하다", word: "restrict" },
  { meaning: "노예", word: "slave" },
  { meaning: "적절한, 적합한", word: "suitable" },
  { meaning: "교향곡", word: "symphony" },
  { meaning: "받아들이다, 인정하다", word: "accept" },
  { meaning: "(죄를) 저지르다,  약속하다, 맡기다", word: "commit " },
  { meaning: "부끄러워하는", word: "ashamed" },
  { meaning: "경쟁하다", word: "compete" },
  { meaning: "넓은, 광범위한", word: "broad" },
  { meaning: "개념", word: "concept" },
  { meaning: "계산하다", word: "calculate" },
  { meaning: "보존하다", word: "conserve" },
  { meaning: "(책, 논문의) 장", word: "chapter" },
  { meaning: "목적지", word: "destination" },
  { meaning: "자비, 자선 단체 구호물자", word: "charity" },
  { meaning: "진화", word: "evolution" },
  { meaning: "계속하다", word: "continue" },
  { meaning: "확장하다", word: "expand" },
  { meaning: "조밀한, 조잡한", word: "dense" },
  { meaning: "진짜의, 성실한", word: "genuine" },
  { meaning: "의지하다", word: "depend" },
  { meaning: "중력", word: "gravity" },
  { meaning: "멸종된", word: "extinct" },
  { meaning: "고용하다", word: "hire" },
  { meaning: "가족, 가정, 가족의", word: "household" },
  { meaning: "고립시키다", word: "isolate" },
  { meaning: "무식한, 모르는", word: "ignorant" },
  { meaning: "논리, 논리학", word: "logic" },
  { meaning: "유아, 유아의, 미발달의", word: "infant" },
  { meaning: "결혼, 혼인", word: "marriage" },
  { meaning: "연구소, 협회, 설립하다, 제정하다", word: "institute" },
  { meaning: "군대, 군대의", word: "military" },
  { meaning: "최근에", word: "lately" },
  { meaning: "재생하다, 복제하다", word: "reproduce" },
  { meaning: "순수한", word: "pure" },
  { meaning: "분별 있는, 현명한", word: "sensible" },
  { meaning: "받다", word: "receive" },
  { meaning: "상태, 지위, 현상", word: "status" },
  { meaning: "반환, 환불, 환불하다", word: "refund" },
  { meaning: "총합, 합계", word: "sum" },
  { meaning: "구조, 구조하다", word: "rescue" },
  { meaning: "흔들리다, 진동하다,  그네", word: "swing" },
  { meaning: "~인 반면에", word: "whereas" },
  { meaning: "어조, 말투, 음, 색조", word: "tone" },
  { meaning: "농업", word: "agriculture" },
  { meaning: "겨냥하다, 조준", word: "aim" },
  { meaning: "분명한, 명백한", word: "apparent" },
  { meaning: "1년의, 1년간의", word: "annual" },
  { meaning: "취소하다", word: "cancel" },
  { meaning: "깨우다, 깨어나다, 깨어있는", word: "awake" },
  { meaning: "동료, 동반자", word: "companion" },
  { meaning: "찬란한, 명석한", word: "brilliant" },
  { meaning: "구성 요소,  구성하고 있는", word: "component" },
  { meaning: "해류, 흐름, 현재", word: "current" },
  { meaning: "출발", word: "departure" },
  { meaning: "민주주의", word: "democracy" },
  { meaning: "내려오다, 물려주다", word: "descend" },
  { meaning: "논증하다, 설명하다,  시위하다, 보여주다", word: "demonstrate" },
  { meaning: "근면한", word: "diligent" },
  { meaning: "필사적인, 절망적인", word: "desperate" },
  { meaning: "별개의, 뚜렷한", word: "distinct" },
  { meaning: "갈망하는", word: "eager" },
  { meaning: "공식적인", word: "formal" },
  { meaning: "신념, 믿음", word: "faith" },
  { meaning: "초대, 초대장", word: "invitation" },
  { meaning: "법률의, 합법의", word: "legal" },
  { meaning: "새는 구멍, 새다", word: "leak" },
  { meaning: "성숙한, 익은,  성숙해지다, 지불 만기의", word: "mature" },
  { meaning: "입자, 미량, 극소량", word: "particle" },
  { meaning: "감정을 상하게 하다,  범죄를 저지르다", word: "offend" },
  { meaning: "일부, 부분, 분할하다", word: "portion" },
  { meaning: "반대하다", word: "oppose" },
  { meaning: "빈곤, 가난", word: "poverty" },
  { meaning: "냉장고", word: "refrigerator" },
  { meaning: "정확한", word: "precise" },
  { meaning: "멀리 떨어진,  희박한 드문", word: "remote" },
  { meaning: "돌아오다, 돌려주다 귀한, 수익", word: "return" },
  { meaning: "여분의, 검소한", word: "spare" },
  { meaning: "(종교적)의식, 의례", word: "rite" },
  { meaning: "이동하다, 옮기다", word: "transfer" },
  { meaning: "조각하다, 조각", word: "sculpture" },
  { meaning: "함정, 덪을 놓다, 막다", word: "trap" },
  { meaning: "시각의", word: "visual" },
  { meaning: "보편적인, 우주의", word: "universal" },
  { meaning: "목적을 이루다, (명성을) 얻다", word: "achieve" },
  { meaning: "나중에, 그 후에", word: "afterward" },
  { meaning: "시민의, 민간의", word: "civil" },
  { meaning: "도착하다", word: "arrive" },
  { meaning: "복잡한, 복합체", word: "complicated" },
  { meaning: "할당하다, 지정하다", word: "assign" },
  { meaning: "소화하다, 요약하다", word: "digest" },
  { meaning: "돈을 걸다, 내기를 걸다 내기", word: "bet" },
  { meaning: "훈련, 훈련하다,  기강, 규율", word: "discipline" },
  { meaning: "고객, (변호사) 의뢰인", word: "client" },
  { meaning: "의무, 관세", word: "duty" },
  { meaning: "악, 사악, 사악한", word: "evil" },
  { meaning: "금지하다", word: "forbid" },
  { meaning: "공상, 공상하다,  좋아함, 화려한", word: "fancy" },
  { meaning: "관대한, 후한", word: "generous" },
  { meaning: "고속도로, 간선도로", word: "highway" },
  { meaning: "통찰, 통찰력", word: "insight" },
  { meaning: "공포, 전율, 공포의", word: "horror" },
  { meaning: "유치원", word: "kindergarten" },
  { meaning: "보험을 계약하다,  안전하게 하다", word: "insure" },
  { meaning: "실험실, 실험실의", word: "laboratory" },
  { meaning: "규제하다, 조절하다", word: "regulate" },
  { meaning: "세탁물", word: "laundry" },
  { meaning: "왕족의, 왕의", word: "royal" },
  { meaning: "강의를 하다, 강의", word: "lecture" },
  { meaning: "파멸, 파산,  폐허로 만들다", word: "ruin" },
  { meaning: "사소한, 부전공하다,  미성년자", word: "minor" },
  { meaning: "부족한, 드문", word: "scarce" },
  { meaning: "선택, 선택권", word: "option" },
  { meaning: "선반", word: "shelf" },
  { meaning: "중단, 중단하다,  잠시 멈추다", word: "pause" },
  { meaning: "외과 수술", word: "surgery" },
  { meaning: "입증하다,  ~으로 판명되다", word: "prove" },
  { meaning: "번영하다, 발전하다", word: "thrive" },
  { meaning: "부족, 결함", word: "shortage" },
  { meaning: "궁극적인, 최후의", word: "ultimate" },
  { meaning: "변형시키다, 변환하다", word: "transform" },
  { meaning: "효용, 공익 설비시설", word: "utility" },
  { meaning: "활력", word: "vigor" },
  { meaning: "예배, 숭배, 숭배하다", word: "worship" },
  { meaning: "추상, 개요, 추상적인", word: "abstract" },
  { meaning: "외국인, 외계인, 외국의, 이질적인", word: "alien" },
  { meaning: "옆에, 제쳐두고", word: "aside" },
  { meaning: "적절한", word: "appropriate" },
  { meaning: "축복하다", word: "bless" },
  { meaning: "바로 잡다, 옳은", word: "correct" },
  { meaning: "우연의 일치,  동시에 일어난 사건", word: "coincidence" },
  { meaning: "대접하다, 식사", word: "dine" },
  { meaning: "확인하다,  (결심을) 굳게하다", word: "confirm" },
  { meaning: "문서, 기록하다", word: "document" },
  { meaning: "동시대의, 현대의", word: "contemporary" },
  { meaning: "실행하다,  사형을 집행하다", word: "execute" },
  { meaning: "오두막집", word: "cottage" },
  { meaning: "움켜쥐다", word: "grab" },
  { meaning: "정중히 거절하다, 하락, 쇠퇴, 하락하다", word: "decline" },
  { meaning: "~에 영감을 주다,  고무시키다, 격려하다", word: "inspire" },
  { meaning: "패배, 패배 시키다", word: "defeat" },
  { meaning: "설치하다", word: "install" },
  { meaning: "설명하다", word: "explain" },
  { meaning: "지성", word: "intellect" },
  { meaning: "융합하다, 전기퓨즈,  도화선", word: "fuse" },
  { meaning: "글자 그대로", word: "literally" },
  { meaning: "설명하다, 예증하다,  삽화를 넣다", word: "illustrate" },
  { meaning: "금지하다", word: "prohibit" },
  { meaning: "모방하다", word: "imitate" },
  { meaning: "제안하다, 청혼하다", word: "propose" },
  { meaning: "측정하다, 측정, 수단", word: "measure" },
  { meaning: "의지하다, 자주가다,  유흥지", word: "resort" },
  { meaning: "필수, 필수품, 필요", word: "necessity" },
  { meaning: "학문, 장학금", word: "scholarship" },
  { meaning: "먹이", word: "prey" },
  { meaning: "향신료, 양념", word: "spice" },
  { meaning: "이전의, 우선하는", word: "prior" },
  { meaning: "~가 아닐까 의심하다,  용의자", word: "suspect" },
  { meaning: "학생, 눈동자, 동공", word: "pupil" },
  { meaning: "유혹하다", word: "tempt" },
  { meaning: "참다, 묵인하다,  용인하다", word: "tolerate" },
  { meaning: "승리, 승리하다", word: "triumph" },
  { meaning: "생산하다, 양보하다,  굴복하다", word: "yield" },
  { meaning: "난파, 조난, 난파선,  난파시키다", word: "wreck" },
  { meaning: "연설하다, 연설, 인사말", word: "address" },
  { meaning: "버리다, 포기하다", word: "abandon" },
  { meaning: "통근, 통근하다", word: "commute" },
  { meaning: "대리점", word: "agency" },
  { meaning: "비교하다", word: "compare" },
  { meaning: "나타나다", word: "appear" },
  { meaning: "반대의, 정반대", word: "contrary" },
  { meaning: "발생하다, 생겨나다", word: "arise" },
  { meaning: "토론, 토론하다", word: "debate" },
  { meaning: "극복하다, 정복하다", word: "conquer" },
  { meaning: "결점, 탈당하다,  망명하다", word: "defect" },
  { meaning: "계약하다, 계약서,  수축시키다", word: "contract" },
  { meaning: "지진", word: "earthquake" },
  { meaning: "기준, 표준", word: "criteria" },
  { meaning: "입학하다, 등록하다", word: "enroll" },
  { meaning: "가뭄", word: "drought" },
  { meaning: "확보하다, 분명히 하다", word: "ensure" },
  { meaning: "고상한, 우아한", word: "elegant" },
  { meaning: "탐욕", word: "greed" },
  { meaning: "비상한, 비범한", word: "extraordinary" },
  { meaning: "거주하다", word: "inhabit" },
  { meaning: "거친, 가혹한", word: "harsh" },
  { meaning: "내부의", word: "inner" },
  { meaning: "부과하다, 강요하다", word: "impose" },
  { meaning: "겸손한, 알맞은", word: "modest" },
  { meaning: "명장, 대작", word: "masterpiece" },
  { meaning: "영양", word: "nutrition" },
  { meaning: "변형하다, 수정하다", word: "modify" },
  { meaning: "영수증", word: "receipt" },
  { meaning: "그럼에도 불구하고", word: "nevertheless" },
  { meaning: "도장, 봉인, 봉인하다", word: "seal" },
  { meaning: "양육, 교육, 양육하다,  교육하다", word: "nurture" },
  { meaning: "찢다, 쪼개다,  쪼개진, 분열", word: "split" },
  { meaning: "편견, 선입견", word: "prejudice" },
  { meaning: "감독하다,  관리하다, 통치하다", word: "supervise" },
  { meaning: "성직자", word: "priest" },
  { meaning: "특성, 특징", word: "trait" },
  { meaning: "등록, 등록하다,  기재하다", word: "register" },
  { meaning: "가상의, 사실상의", word: "virtual" },
  { meaning: "소매, 소매하다", word: "retail" },
  { meaning: "청소년기의, 청소년", word: "adolescent" },
  { meaning: "연관 짓다, 교체하다,  동료", word: "associate" },
  { meaning: "북극의", word: "arctic" },
  { meaning: "방해, 장애물", word: "barrier" },
  { meaning: "붙잡다, 포획하다, 포획", word: "capture" },
  { meaning: "승무원", word: "crew" },
  { meaning: "의식하고 있는, 의식", word: "conscious" },
  { meaning: "잔인한", word: "cruel" },
  { meaning: "협회, 협의회", word: "council" },
  { meaning: "묽은, 희석시키다", word: "dilute" },
  { meaning: "부인하다, 거절하다", word: "deny" },
  { meaning: "구별하다", word: "distinguish" },
  { meaning: "박탈하다", word: "deprive" },
  { meaning: "심부름, 잡일", word: "errand" },
  { meaning: "흐릿한, 어두운,  흐려지다, 멍한", word: "dim" },
  { meaning: "수치, 계산, 형체, 계산하다", word: "figure" },
  { meaning: "제거하다, 삭제하다", word: "eliminate" },
  { meaning: "접다", word: "fold" },
  { meaning: "일반적인, (육군, 공군, 해병대) 대장", word: "general" },
  { meaning: "흘긋 봄, 흘긋 보다", word: "glance" },
  { meaning: "빛나다, 번쩍임", word: "glare" },
  { meaning: "화나게 하다,  짜증나게 하다", word: "irritate" },
  { meaning: "방해하다, 간섭하다", word: "interfere" },
  { meaning: "보행자, 보행자의", word: "pedestrian" },
  { meaning: "일상적인 일, 일상적인", word: "routine" },
  { meaning: "우세하다, 보급되다,  유행하다", word: "prevail" },
  { meaning: "절규, 절규하다", word: "scream" },
  { meaning: "깊은, 심오한", word: "profound" },
  { meaning: "민감한, 신경과민의", word: "sensitive" },
  { meaning: "진술, 성명서", word: "statement" },
  { meaning: "엎지르다, 흘리다,  엎지름", word: "spill" },
  { meaning: "전통, 관습", word: "tradition" },
  { meaning: "삼키다, 삼킴, 제비", word: "swallow" },
  { meaning: "시도, 실험, 재판", word: "trial" },
  { meaning: "일시적인, 임시의", word: "temporary" },
  { meaning: "부족, 종족", word: "tribe" },
  { meaning: "비극의, 비참한, 비장한", word: "tragic" },
  { meaning: "창고", word: "warehouse" },
  { meaning: "보통의, 일상의", word: "usual" },
  { meaning: "복지", word: "welfare" },
  { meaning: "조절하다, 조정하다", word: "adjust" },
  { meaning: "(가정용) 기구, 장치", word: "appliance" },
  { meaning: "원자", word: "atom" },
  { meaning: "명령하다, 지휘하다,  명령", word: "command" },
  { meaning: "후보자", word: "candidate" },
  { meaning: "빚, 부채", word: "debt" },
  { meaning: "격렬한, 과감한", word: "drastic" },
  { meaning: "표류, 표류하다", word: "drift" },
  { meaning: "위험에 빠뜨리다", word: "endanger" },
  { meaning: "생태계", word: "ecosystem" },
  { meaning: "풍성하게 하다,  부유하게 하다", word: "enrich" },
  { meaning: "인종의, 민족의", word: "ethnic" },
  { meaning: "사라지다, 희미해지다", word: "fade" },
  { meaning: "초과, 초과량, 여분의", word: "excess" },
  { meaning: "미생물, 세균", word: "germ" },
  { meaning: "명성", word: "fame" },
  { meaning: "감염, 전염", word: "infection" },
  { meaning: "예언하다, 예고하다", word: "foretell" },
  { meaning: "귀족의, 고결한", word: "noble" },
  { meaning: "게다가", word: "furthermore" },
  { meaning: "동료, 동년배", word: "peer" },
  { meaning: "이상, 이상적인", word: "ideal" },
  { meaning: "축적, 쌓아올린 더미,  축적하다, 쌓아올리다", word: "pile" },
  { meaning: "낮잠, 낮잠 자다", word: "nap" },
  { meaning: "전진하다, 전진, 진보", word: "progress" },
  { meaning: "구두의, 구술의", word: "oral" },
  { meaning: "보호하다", word: "protect" },
  { meaning: "현실화하다, 깨닫다", word: "realize" },
  { meaning: "강화, 보강", word: "reinforcement" },
  { meaning: "대표, 대표하는,  국회의원", word: "representative" },
  { meaning: "새롭게 하다, 갱신하다", word: "renew" },
  { meaning: "결과로서 생기다, 결과", word: "result" },
  { meaning: "수선[수리]하다, 수선, (건강 등을)회복하다", word: "repair" },
  { meaning: "변화, 이동, 바꾸다,  교대 근무조", word: "shift" },
  { meaning: "굳어지다", word: "stiffen" },
  { meaning: "엄한, 엄격한", word: "strict" },
  { meaning: "무기, 병기", word: "weapon" },
  { meaning: "도매, 도매의", word: "wholesale" },
  { meaning: "널리 퍼진", word: "widespread" },
  { meaning: "이상하게 여기다", word: "wonder" },
  { meaning: "피하다", word: "avoid" },
  { meaning: "부딪치다, 충돌하다,  충돌, 혹, 솟아오른 곳", word: "bump" },
  { meaning: "턱수염", word: "beard" },
  { meaning: "그만두다, 중지하다", word: "cease" },
  { meaning: "직면하다", word: "confront" },
  { meaning: "천장, 상한선", word: "ceiling" },
  { meaning: "분쇄하다, 뭉개다", word: "crush" },
  { meaning: "전투, 싸우다", word: "combat" },
  { meaning: "헌납하다, 바치다", word: "dedicate" },
  { meaning: "솜씨, 공예, 기능 선박, 비행기", word: "craft" },
  { meaning: "운명", word: "destiny" },
  { meaning: "~할 운명이다, 운명 비운, 멸망", word: "doom" },
  { meaning: "배치하다, 처리하다,  ~할 마음이 내키게 하다", word: "dispose" },
  { meaning: "삭제하다, 지우다", word: "erase" },
  { meaning: "왕조, 왕가", word: "dynasty" },
  { meaning: "존재하다, 살아가다", word: "exist" },
  { meaning: "전체의, 완전한 전부, 전체", word: "entire" },
  { meaning: "도박, 도박을 하다", word: "gamble" },
  { meaning: "달아나다, 벗어나다 탈출, 도망", word: "escape" },
  { meaning: "장르, 유형, 형식", word: "genre" },
  { meaning: "고난, 역경", word: "hardship" },
  { meaning: "아주 적은, 최소의", word: "minimal" },
  { meaning: "급함, 서두름", word: "haste" },
  { meaning: "관점, 견해, 원근법 전망", word: "perspective" },
  { meaning: "수소", word: "hydrogen" },
  { meaning: "주요한, 첫째의, 초기의", word: "primary" },
  { meaning: "처음의, 머리글자", word: "initial" },
  { meaning: "뗏목, 고무보트", word: "raft" },
  { meaning: "잘못 인도하다", word: "mislead" },
  { meaning: "논평, 비평, 재검토,  재검토하다", word: "review" },
  { meaning: "최상의, 최적의", word: "optimal" },
  { meaning: "흩뿌리다, 산란시키다", word: "scatter" },
  { meaning: "눈에 띄는, 저명한,  미해결의", word: "outstanding" },
  { meaning: "적시다, 젖다, 흡수하다", word: "soak" },
  { meaning: "가라앉다", word: "sink" },
  { meaning: "성질, 기질, 완화하다", word: "temper" },
  { meaning: "실, 실을 꿰다", word: "thread" },
  { meaning: "의심할 여지없이, 확실히", word: "undoubtedly" },
  { meaning: "타당한, 유용한", word: "valid" },
  { meaning: "통합하다, 통일하다", word: "unify" },
  { meaning: "골동품, 고미술의", word: "antique" },
  { meaning: "조상, 선조", word: "ancestor" },
  { meaning: "예산, 예산안", word: "budget" },
  { meaning: "교환하다, 물물교환,  교역품", word: "barter" },
  { meaning: "명성, 유명인사", word: "celebrity" },
  { meaning: "쌀쌀한, 냉담한", word: "chilly" },
  { meaning: "해고하다, 해산시키다 묵살하다", word: "dismiss" },
  { meaning: "원의, 순환의", word: "circular" },
  { meaning: "부서지기 쉬운", word: "fragile" },
  { meaning: "밀집, 혼잡", word: "congestion" },
  { meaning: "부드러운 털, 모피", word: "fur" },
  { meaning: "구성하다, 제정하다,  설립하다", word: "constitute" },
  { meaning: "기하학", word: "geometry" },
  { meaning: "만족하여, 내용(물), 목차", word: "content" },
  { meaning: "빙하", word: "glacier" },
  { meaning: "기어가다, 서행하다", word: "crawl" },
  { meaning: "풀을 뜯다, 방목하다", word: "graze" },
  { meaning: "당뇨병", word: "diabetes" },
  { meaning: "일어난 일, 사건,  일어나기 쉬운", word: "incident" },
  { meaning: "불명예", word: "disgrace" },
  { meaning: "무관심한", word: "indifferent" },
  { meaning: "사설, 논설, 편집자의", word: "editorial" },
  { meaning: "재료, 성분", word: "ingredient" },
  { meaning: "사나운, 맹렬한", word: "fierce" },
  { meaning: "온건한, 적당한", word: "moderate" },
  { meaning: "흐르다, 흐름", word: "flow" },
  { meaning: "신화, 사회적 통념", word: "myth" },
  { meaning: "상속하다,  유전으로 이어받다", word: "inherit" },
  { meaning: "명백한, 분명한", word: "obvious" },
  { meaning: "조사하다, 수사하다", word: "investigate" },
  { meaning: "회의, 비평, 수업시간, (대학의) 학기", word: "session" },
  { meaning: "장애물, 방해가 되는 것", word: "obstacle" },
  { meaning: "구체, 구", word: "sphere" },
  { meaning: "이익, 이윤, 이자 이익을 얻다", word: "profit" },
  { meaning: "긴장시키다,  팽팽하게 하다, 긴장", word: "strain" },
  { meaning: "거친, 난폭한, 대강의", word: "rough" },
  { meaning: "촉구하다, 강요하다", word: "urge" },
  { meaning: "긁다, 할퀴다, 긁은 자국", word: "scratch" },
  { meaning: "생명의, 매우 중요한", word: "vital" },
  { meaning: "막연한, 모호한, 흐릿한", word: "vague" },
  { meaning: "폐지하다", word: "abolish" },
  { meaning: "관리하다, 운영하다 통치하다", word: "administer" },
  { meaning: "보증하다, 확실하게 하다", word: "assure" },
  { meaning: "자산, 자질", word: "asset" },
  { meaning: "후방에, 뒤쪽으로,  거꾸로", word: "backward" },
  { meaning: "(감탄하며) 외치다", word: "exclaim" },
  { meaning: "베다, 새기다, 조각하다", word: "carve" },
  { meaning: "맛, 맛을 내다", word: "flavor" },
  { meaning: "집안일, 허드렛일", word: "chore" },
  { meaning: "유산, 세습 재산", word: "heritage" },
  { meaning: "부식, 부식하다,  쇠퇴하다", word: "decay" },
  { meaning: "도장을 찍다, 감명시키다, 찍은 자국, 인상", word: "imprint" },
  { meaning: "살다, 거주하다", word: "dwell" },
  { meaning: "정당화하다", word: "justify" },
  { meaning: "황제", word: "emperor" },
  { meaning: "층, 겹", word: "layer" },
  { meaning: "비옥한, 기름진", word: "fertile" },
  { meaning: "군주", word: "lord" },
  { meaning: "형성하다, 형태", word: "form" },
  { meaning: "닦다, 윤내다 (문장 등을) 다듬다", word: "polish" },
  { meaning: "화석", word: "fossil" },
  { meaning: "묘사하다, 설명하다,  초상을 그리다", word: "portray" },
  { meaning: "성, 성별", word: "gender" },
  { meaning: "도자기", word: "pottery" },
  { meaning: "반짝이다, 반짝임", word: "glitter" },
  { meaning: "재산", word: "property" },
  { meaning: "혁신", word: "innovation" },
  { meaning: "빛나는, 아주 밝은", word: "radiant" },
  { meaning: "반대자, 상대, 반대하는", word: "opponent" },
  { meaning: "정밀 검사하다,  유심히 쳐다보다", word: "scan" },
  { meaning: "제출하다, 나타내다,  현재의, 선물", word: "present" },
  { meaning: "노력하다, 애쓰다 투쟁하다", word: "strive" },
  { meaning: "단백질", word: "protein" },
  { meaning: "정기 구독하다", word: "subscribe" },
  { meaning: "상쾌하게 하다,  새롭게 하다", word: "refresh" },
  { meaning: "대체하다, 대체물,  대리자", word: "substitute" },
  { meaning: "리허설, 시연, 예행연습", word: "rehearsal" },
  { meaning: "(생물의 근육, 신경 등의) 조직", word: "tissue" },
  { meaning: "번역하다, 옮기다", word: "translate" },
  { meaning: "급료", word: "wage" },
  { meaning: "고발하다, 비난하다", word: "accuse" },
  { meaning: "각도, 모서리", word: "angle" },
  { meaning: "소중히 하다", word: "cherish" },
  { meaning: "적용하다", word: "apply" },
  { meaning: "동료", word: "colleague" },
  { meaning: "결속, 속박, 약정, 채권", word: "bond" },
  { meaning: "회담, 회의", word: "conference" },
  { meaning: "(집합적)소, 소떼", word: "cattle" },
  { meaning: "구리, 구리의, 구리빛의", word: "copper" },
  { meaning: "조심, 주의, 주의하다", word: "caution" },
  { meaning: "버리다, 처분하다", word: "discard" },
  { meaning: "대처하다, 잘 처리하다", word: "cope" },
  { meaning: "영원한", word: "eternal" },
  { meaning: "묘사하다, 그리다", word: "depict" },
  { meaning: "굶주림, 기아", word: "famine" },
  { meaning: "향상시키다", word: "enhance" },
  { meaning: "친밀한", word: "intimate" },
  { meaning: "면역성의, 면제의", word: "immune" },
  { meaning: "(로켓을)발사하다, 발사 (새로운 일을)시작하다", word: "launch" },
  { meaning: "대출, 대출금, 대출하다", word: "loan" },
  { meaning: "위엄, 장엄, 왕(M-)", word: "majesty" },
  { meaning: "유순한, 순종하는", word: "obedient" },
  { meaning: "장점, 공로, ~할 만하다", word: "merit" },
  { meaning: "고집하다, 지속하다", word: "persist" },
  { meaning: "궤도,  궤도를 그리며 돌다", word: "orbit" },
  { meaning: "절차, 과정", word: "procedure" },
  { meaning: "압도하다,  당황하게 하다", word: "overwhelm" },
  { meaning: "과격한, 급진적인,  근본적인, 급진주의자", word: "radical" },
  { meaning: "알약", word: "pill" },
  { meaning: "날 것의, 가공하지 않은", word: "raw" },
  { meaning: "환영회, 접수", word: "reception" },
  { meaning: "역, 반대, 역의, 반대의 되돌리다", word: "reverse" },
  { meaning: "축소하다, 수축하다", word: "shrink" },
  { meaning: "끈, 끈으로 꿴 것, 줄", word: "string" },
  { meaning: "(어깨를) 으쓱하다", word: "shrug" },
  { meaning: "미묘한, 희미한", word: "subtle" },
  { meaning: "전달하다", word: "transmit" },
  { meaning: "우월한, 상사", word: "superior" },
  { meaning: "사악한, 악의 있는", word: "vicious" },
  { meaning: "치료, 요법", word: "therapy" },
  { meaning: "방심하지 않는, 기민한", word: "alert" },
  { meaning: "적당한", word: "adequate" },
  { meaning: "건축, 건축물", word: "architecture" },
  { meaning: "분류하다", word: "classify" },
  { meaning: "놀라게 하다", word: "astonish" },
  { meaning: "섬세한", word: "delicate" },
  { meaning: "(주의·흥미 등을) 끌다", word: "attract" },
  { meaning: "경험하다, 경험, 체험", word: "experience" },
  { meaning: "금지, 금지하다", word: "ban" },
  { meaning: "근본, 근본의, 근본적인", word: "fundamental" },
  { meaning: "범주", word: "category" },
  { meaning: "졸업하다, 졸업생, 대학원 학생", word: "graduate" },
  { meaning: "아담한, 밀집한,  꽉 채우다", word: "compact" },
  { meaning: "(날씨가) 습기 있는,  눅눅한", word: "humid" },
  { meaning: "절망, 절망하다", word: "despair" },
  { meaning: "팽창시키다  자만하게 하다", word: "inflate" },
  { meaning: "(얼굴이) 붉어지다, 물이 쏟아져 나오다", word: "flush" },
  { meaning: "이음매, 관절 공동의, 연합의", word: "joint" },
  { meaning: "장례식, 장례의", word: "funeral" },
  { meaning: "충성스러운, 성실한", word: "loyal" },
  { meaning: "그러므로, 지금부터", word: "hence" },
  { meaning: "대리석, 구슬, 대리석의", word: "marble" },
  { meaning: "창피함, 굴욕", word: "humiliation" },
  { meaning: "낙관적인, 낙천적인", word: "optimistic" },
  { meaning: "마찬가지로", word: "likewise" },
  { meaning: "통행, 통과 (인용문의) 한 절", word: "passage" },
  { meaning: "살인, 살인하다", word: "murder" },
  { meaning: "수동적인, 간접의", word: "passive" },
  { meaning: "생략하다, 빼다", word: "omit" },
  { meaning: "의사, 내과의사", word: "physician" },
  { meaning: "결과", word: "outcome" },
  { meaning: "~을 선호하다", word: "prefer" },
  { meaning: "갑작스런 공포, 공황 공황적인", word: "panic" },
  { meaning: "주장하다, ~인 척하다", word: "pretend" },
  { meaning: "전략", word: "strategy" },
  { meaning: "복구하다, 재건하다 회복하다", word: "restore" },
  { meaning: "영토", word: "territory" },
  { meaning: "(물건을 담는) 용기, 배 선박, 혈관", word: "vessel" },
  { meaning: "황무지, 황야", word: "wilderness" },
  { meaning: "~에 의하여,  ~를 거쳐서(경유해서)", word: "via" },
  { meaning: "걱정, 불안, 열망", word: "anxiety" },
  { meaning: "예상하다, 기대하다", word: "anticipate" },
  { meaning: "이익, 자기편", word: "behalf" },
  { meaning: "(몸.노력.시간.돈)바치다", word: "devote" },
  { meaning: "싹, 싹트다", word: "bud" },
  { meaning: "감소하다, 감소시키다", word: "diminish" },
  { meaning: "부산물", word: "by-product" },
  { meaning: "이산화물", word: "dioxide" },
  { meaning: "~에 관계하다, 관심사 걱정", word: "concern" },
  { meaning: "왜곡, 찌그러뜨림", word: "distortion" },
  { meaning: "싸우다, 경쟁하다 주장하다", word: "contend" },
  { meaning: "배제하다, 제외하다", word: "exclude" },
  { meaning: "버젓한, 품위 있는", word: "decent" },
  { meaning: "융통성 있는,  구부리기 쉬운", word: "flexible" },
  { meaning: "먹을 수 있는, 식용의", word: "edible" },
  { meaning: "무한의", word: "infinite" },
  { meaning: "연방의, 연합의", word: "federal" },
  { meaning: "질투하는", word: "jealous" },
  { meaning: "액체, 액체의", word: "liquid" },
  { meaning: "절뚝거리는 기운이 없는", word: "limp" },
  { meaning: "전망, 조망", word: "outlook" },
  { meaning: "지방(자치제)의, 시의", word: "municipal" },
  { meaning: "준비하다", word: "prepare" },
  { meaning: "(후보자로) 지명되다 추천하다", word: "nominate" },
  { meaning: "(정처 없이) 배회하다", word: "roam" },
  { meaning: "보도, 포장도로", word: "pavement" },
  { meaning: "안정된, 마구간", word: "stable" },
  { meaning: "영세 농민, 소작농", word: "peasant" },
  { meaning: "충분한", word: "sufficient" },
  { meaning: "현상, 사건 비범한 인물", word: "phenomenon" },
  { meaning: "동정, 동감", word: "sympathy" },
  { meaning: "신성한, 성스러운", word: "sacred" },
  { meaning: "(의학) 정제, 알약 평평한 판", word: "tablet" },
  { meaning: "고통을 받다", word: "suffer" },
  { meaning: "교환하다, 무역", word: "trade" },
  { meaning: "상징적인", word: "symbolic" },
  { meaning: "거래, 처리", word: "transaction" },
  { meaning: "세입자, 주민", word: "tenant" },
  { meaning: "사소한", word: "trivial" },
  { meaning: "~할 가치가 있는", word: "worthwhile" },
  { meaning: "갑작스러운", word: "abrupt" },
  { meaning: "대서양, 대서양의", word: "Atlantic" },
  { meaning: "무너지다, 붕괴하다", word: "collapse" },
  { meaning: "칸막이 한 좌석,  부스, 매점", word: "booth" },
  { meaning: "관리하다, 지배, 제어", word: "control" },
  { meaning: "의도적인, 신중한,  숙고하다", word: "deliberate" },
  { meaning: "(정신의) 산만함,  주의산만, 기분 전환", word: "distraction" },
  { meaning: "분출하다, 폭발하다", word: "erupt" },
  { meaning: "다른 종류의, 다양한", word: "diverse" },
  { meaning: "운명", word: "fate" },
  { meaning: "동적인, 역학의", word: "dynamic" },
  { meaning: "뚫어지게 보다 응시하다", word: "gaze" },
  { meaning: "어둠, 우울", word: "gloom" },
  { meaning: "산업(계), 공업", word: "industry" },
  { meaning: "빙산", word: "iceberg" },
  { meaning: "모욕, 모욕하다", word: "insult" },
  { meaning: "내부의", word: "internal" },
  { meaning: "전쟁의, 군대의", word: "martial" },
  { meaning: "포유동물", word: "mammal" },
  { meaning: "서로의, 공통의", word: "mutual" },
  { meaning: "화폐의", word: "monetary" },
  { meaning: "부분적인", word: "partial" },
  { meaning: "독백", word: "monologue" },
  { meaning: "음모, 계획, 줄거리 음모를 꾸미다", word: "plot" },
  { meaning: "신경", word: "nerve" },
  { meaning: "규정하다 (약을) 처방하다", word: "prescribe" },
  { meaning: "즉각적인 촉구하다, 자극하다", word: "prompt" },
  { meaning: "대단히 소중한", word: "priceless" },
  { meaning: "정제하다, 맑게 하다", word: "refine" },
  { meaning: "추구하다, 쫓다", word: "pursue" },
  { meaning: "분개하다, 화를 내다", word: "resent" },
  { meaning: "막대기, 회초리", word: "rod" },
  { meaning: "개정하다", word: "revise" },
  { meaning: "제안하다, 암시하다", word: "suggest" },
  { meaning: "최고의, 훌륭한", word: "superb" },
  { meaning: "최고, 최고의", word: "supreme" },
  { meaning: "떠받치다, 지지하다 떠받침, 지지", word: "support" },
  { meaning: "방아쇠, 계기, 유발하다", word: "trigger" },
  { meaning: "매달다, 중지하다", word: "suspend" },
  { meaning: "이상한, 기묘한", word: "weird" },
  { meaning: "경주[경쟁]하다, 질주 질주하다", word: "race" },
  { meaning: "남용, 욕설, 학대 남용하다, 학대하다", word: "abuse" },
  { meaning: "오솔길, 골목길", word: "alley" },
  { meaning: "공격적인, 적극적인", word: "aggressive" },
  { meaning: "놀라게 하다", word: "astound" },
  { meaning: "~의 탓으로 돌리다,  속성", word: "attribute" },
  { meaning: "소책자, 브로셔", word: "brochure" },
  { meaning: "청사진 청사진을 작성하다", word: "blueprint" },
  { meaning: "성원하다, 환호, 갈채", word: "cheer" },
  { meaning: "고장, 쇠약", word: "breakdown" },
  { meaning: "전후 관계, 문맥", word: "context" },
  { meaning: "완료하다,  완전한", word: "complete" },
  { meaning: "중대한, 결정적인", word: "crucial" },
  { meaning: "치료하다, 치유, 회복", word: "cure" },
  { meaning: "교육 과정, 커리큘럼", word: "curriculum" },
  { meaning: "변장, 변장시키다", word: "disguise" },
  { meaning: "갑판", word: "deck" },
  { meaning: "육성하다, 촉진시키다 수양의, 위탁의", word: "foster" },
  { meaning: "독재자, 구술자 받아쓰게 하는 사람", word: "dictator" },
  { meaning: "비참한, 불쌍한", word: "miserable" },
  { meaning: "지배하다", word: "dominate" },
  { meaning: "생산(고), 산출(량)", word: "output" },
  { meaning: "강요하다, 힘", word: "force" },
  { meaning: "연기하다, 뒤로 미루다", word: "postpone" },
  { meaning: "눈살을 찌뿌리다 찡그린 얼굴", word: "frown" },
  { meaning: "심리학자", word: "psychologist" },
  { meaning: "얻다, 이익", word: "gain" },
  { meaning: "뒤, 뒤의, 후방의 기르다, 일으키다", word: "rear" },
  { meaning: "지레, 레버 지레를 쓰다", word: "lever" },
  { meaning: "훔치다, 강탈하다", word: "rob" },
  { meaning: "남자의, 남자다운", word: "masculine" },
  { meaning: "설교", word: "sermon" },
  { meaning: "마비", word: "paralysis" },
  { meaning: "싹, 싹이 트다", word: "sprout" },
  { meaning: "꿰매다, 바느질하다", word: "sew" },
  { meaning: "괴롭히다, 약올리다", word: "tease" },
  { meaning: "운송 수단, 탈것", word: "vehicle" },
  { meaning: "양철, 주석", word: "tin" },
  { meaning: "조끼, (권리를) 부여하다", word: "vest" },
  { meaning: "실업의, 실직한", word: "unemployed" },
  { meaning: "사건, 일", word: "affair" },
  { meaning: "기다리다", word: "await" },
  { meaning: "만", word: "bay" },
  { meaning: "보상하다", word: "compensate" },
  { meaning: "게시, 게시물", word: "bulletin" },
  { meaning: "구체적인, 콘크리트", word: "concrete" },
  { meaning: "질식 시키다,  숨이 막히다", word: "choke" },
  { meaning: "갈라진 틈, 금가다", word: "crack" },
  { meaning: "집회, 총회, 관습", word: "convention" },
  { meaning: "낙담시키다, 단념시키다", word: "discourage" },
  { meaning: "새벽, 날이 새다 이해되기 시작하다", word: "dawn" },
  { meaning: "치명적인", word: "fatal" },
  { meaning: "다루다, 처리하다, 거래", word: "deal" },
  { meaning: "적대적인", word: "hostile" },
  { meaning: "황폐 시키다", word: "devastate" },
  { meaning: "거꾸로 하다", word: "invert" },
  { meaning: "유동체, 유동체의", word: "fluid" },
  { meaning: "임대, 임대하다", word: "lease" },
  { meaning: "호의, 친선", word: "goodwill" },
  { meaning: "(풀을) 베다", word: "mow" },
  { meaning: "영양분을 주다, 기르다", word: "nourish" },
  { meaning: "인내심", word: "perseverance" },
  { meaning: "간과하다, 내려다보다 너그럽게 봐주다", word: "overlook" },
  { meaning: "꿰뚫다, ~에 구멍을 뚫다", word: "pierce" },
  { meaning: "인내심이 있는, 환자", word: "patient" },
  { meaning: "인종의, 민족의", word: "racial" },
  { meaning: "수확하다", word: "reap" },
  { meaning: "통치, 통치하다", word: "reign" },
  { meaning: "모집하다, 징집하다 신병, 신입사원", word: "recruit" },
  { meaning: "존중하다, 존경", word: "respect" },
  { meaning: "개혁, 개혁하다", word: "reform" },
  { meaning: "지배하다, 지배, 규칙", word: "rule" },
  { meaning: "거절하다, 버리다", word: "reject" },
  { meaning: "만족시키다, 채우다", word: "satisfy" },
  { meaning: "기절 시키다,  멍하게 하다, 놀래다", word: "stun" },
  { meaning: "깜짝 놀라게 하다", word: "startle" },
  { meaning: "무리, 떼, 군대, 군사", word: "troop" },
  { meaning: "긴장, 불안, 긴장시키다.", word: "tension" },
  { meaning: "작업장, 공동 연구회 워크숍", word: "workshop" },
  { meaning: "쟁반", word: "tray" },
  { meaning: "충실하다, 집착하다 고수하다", word: "adhere" },
  { meaning: "괴롭히다", word: "afflict" },
  { meaning: "생기있게하다, 고무하다 살아 있는", word: "animate" },
  { meaning: "통일성 있는, 조리 있는", word: "coherent" },
  { meaning: "2개 국어의", word: "bilingual" },
  { meaning: "발전하다, 진화하다", word: "evolve" },
  { meaning: "공헌하다", word: "contribute" },
  { meaning: "예증하다, 예시하다", word: "exemplify" },
  { meaning: "전환하다", word: "convert" },
  { meaning: "민간 설화, 전설", word: "folktale" },
  { meaning: "핵심, 핵심의", word: "core" },
  { meaning: "분수, 근원", word: "fountain" },
  { meaning: "존엄", word: "dignity" },
  { meaning: "거대한", word: "gigantic" },
  { meaning: "차별하다, 구별하다", word: "discriminate" },
  { meaning: "신랑", word: "groom" },
  { meaning: "시대", word: "era" },
  { meaning: "본능", word: "instinct" },
  { meaning: "(타국에서) 이주하다", word: "immigrate" },
  { meaning: "참을 수 없는", word: "intolerable" },
  { meaning: "판단하다, 재판관", word: "judge" },
  { meaning: "읽고 쓸 수 있는", word: "literate" },
  { meaning: "유지하다, 지지하다", word: "maintain" },
  { meaning: "명상하다", word: "meditate" },
  { meaning: "해악, 장난", word: "mischief" },
  { meaning: "독특한", word: "peculiar" },
  { meaning: "공지하다, 알리다", word: "notify" },
  { meaning: "예방하다", word: "prevent" },
  { meaning: "유명한, 명성 있는", word: "renowned" },
  { meaning: "정렬시키다, 범위", word: "range" },
  { meaning: "창", word: "spear" },
  { meaning: "제거하다", word: "remove" },
  { meaning: "치다 (머릿속에) 떠오르다", word: "strike" },
  { meaning: "위함, 목적", word: "sake" },
  { meaning: "억압하다, 참다", word: "suppress" },
  { meaning: "위생", word: "sanitation" },
  { meaning: "부드러운, 입찰하다 입찰", word: "tender" },
  { meaning: "동시에", word: "simultaneously" },
  { meaning: "(돈을) 인출하다 철수시키다, 철회하다", word: "withdraw" },
  { meaning: "초자연적인", word: "supernatural" },
  { meaning: "불합리한 우스꽝스러운", word: "absurd" },
  { meaning: "박수갈채", word: "applause" },
  { meaning: "바꾸다, 변경하다", word: "alter" },
  { meaning: "깃발, 현수막", word: "banner" },
  { meaning: "대담한, 선이 굵은", word: "bold" },
  { meaning: "자랑하다, 떠벌리다", word: "boast" },
  { meaning: "우연한, 무심결의 격식을 차리지 않는", word: "casual" },
  { meaning: "전문병원, 개인병원", word: "clinic" },
  { meaning: "식민지, 공동체, 군생", word: "colony" },
  { meaning: "강제적인, 강박의", word: "compulsive" },
  { meaning: "칭찬, 칭찬하다", word: "compliment" },
  { meaning: "숨기다", word: "conceal" },
  { meaning: "생각해내다,  ~을 마음에 그리다", word: "conceive" },
  { meaning: "공자의, 유교의", word: "Confucian" },
  { meaning: "배달하다", word: "deliver" },
  { meaning: "뜨다, 떠다니다, 부유물", word: "float" },
  { meaning: "파괴하다", word: "destroy" },
  { meaning: "공식, 이유식, 분유", word: "formula" },
  { meaning: "기숙사", word: "dormitory" },
  { meaning: "격려, 자극, 장려금 격려하는, 자극하는", word: "incentive" },
  { meaning: "내구성", word: "durability" },
  { meaning: "영양실조", word: "malnutrition" },
  { meaning: "직면하다, 얼굴, 표면", word: "face" },
  { meaning: "중립의, 공평한", word: "neutral" },
  { meaning: "붙잡다, 이해하다 파악하다", word: "grasp" },
  { meaning: "관련시키다", word: "relate" },
  { meaning: "전부의, 전체적인 작업복", word: "overall" },
  { meaning: "퇴각, 후퇴 퇴각하다, 후퇴하다", word: "retreat" },
  { meaning: "특정한, 개개의 사항. 상세", word: "particular" },
  { meaning: "감각, 느낌 대사건(센세이션)", word: "sensation" },
  { meaning: "~하는 경향이 있는", word: "prone" },
  { meaning: "얼룩, 얼룩지게 하다", word: "stain" },
  { meaning: "얕은, 얇은, 피상적인 천박한", word: "shallow" },
  { meaning: "경향, 추세", word: "tendency" },
  { meaning: "꼭대기, 정상", word: "summit" },
  { meaning: "겪다", word: "undergo" },
  { meaning: "미신", word: "superstition" },
  { meaning: "맹세, 맹세하다", word: "vow" },
  { meaning: "울다", word: "weep" },
  { meaning: "(일과)씨름하다, 싸우다 레슬링하다", word: "wrestle" },
  { meaning: "밑그림, 원고 초안을 그리다", word: "draft" },
  { meaning: "모으다, 축적하다", word: "accumulate" },
  { meaning: "가공하지 않은, 조잡한", word: "crude" },
  { meaning: "야심 있는", word: "ambitious" },
  { meaning: "보충, 보충하다", word: "supplement" },
  { meaning: "공격하다, 공격", word: "attack" },
  { meaning: "속력", word: "velocity" },
  { meaning: "출석하다, 보살피다", word: "attend" },
  { meaning: "길들여진, 길들이다", word: "tame" },
  { meaning: "경계, 경계선", word: "boundary" },
  { meaning: "분자", word: "molecule" },
  { meaning: "특징, 특성, 독특한 특징적인", word: "characteristic" },
  { meaning: "갈대, 갈대의", word: "reed" },
  { meaning: "한정하다, 감금하다 한계", word: "confine" },
  { meaning: "실망시키다, 낙담시키다 걱정, 실망", word: "dismay" },
  { meaning: "이루어져 있다", word: "consist" },
  { meaning: "진단하다", word: "diagnose" },
  { meaning: "급파, 발송 급파하다, 발송하다", word: "dispatch" },
  { meaning: "~대, ~와 대비하여", word: "versus" },
  { meaning: "구체화하다, 구현하다", word: "embody" },
  { meaning: "저장소, 저수지", word: "reservoir" },
  { meaning: "공평", word: "equity" },
  { meaning: "적합하게 하다 순응시키다", word: "conform" },
  { meaning: "충동, 추진", word: "impulse" },
  { meaning: "넓은, 훤히 트인", word: "spacious" },
  { meaning: "본래대로의,  손상되지 않은", word: "intact" },
  { meaning: "엮다, 짜다", word: "weave" },
  { meaning: "조종하다, 항해하다 길을 찾다", word: "navigate" },
  { meaning: "의식, 식, 의례", word: "ceremony" },
  { meaning: "탄원, 간청, 변명", word: "plea" },
  { meaning: "동기(행동의 원인)", word: "motive" },
  { meaning: "숙달된", word: "proficient" },
  { meaning: "현저한, 저명한", word: "prominent" },
  { meaning: "빼다", word: "subtract" },
  { meaning: "고고학", word: "archaeology" },
  { meaning: "잘라내다, 다듬다", word: "trim" },
  { meaning: "완고한", word: "rigid" },
  { meaning: "최대한의, 최대한도", word: "utmost" },
  { meaning: "열등한", word: "inferior" },
  { meaning: "침해하다, 위반하다", word: "violate" },
  { meaning: "일화, 비화", word: "anecdote" },
  { meaning: "끈, (전기) 코드", word: "cord" },
  { meaning: "서투른, 어색한 꼴사나운", word: "awkward" },
  { meaning: "축축한, 습기", word: "damp" },
  { meaning: "벽장", word: "closet" },
  { meaning: "배출, 내보냄, 방출 배출~, 내보내다, 해고~", word: "discharge" },
  { meaning: "(비용이) 들다 비용, 대가", word: "cost" },
  { meaning: "폭발하다", word: "explode" },
  { meaning: "발견하다", word: "detect" },
  { meaning: "일시적 유행", word: "fad" },
  { meaning: "지름, 직경", word: "diameter" },
  { meaning: "번영하다, 번창하다", word: "flourish" },
  { meaning: "드러내다, 폭로하다", word: "disclose" },
  { meaning: "환상, 착각", word: "illusion" },
  { meaning: "전시하다, 보여주다 전시, 전시품", word: "exhibit" },
  { meaning: "오래 머물다, 계속되다", word: "linger" },
  { meaning: "드러내다 (비밀을) 폭로하다", word: "expose" },
  { meaning: "언어의, 언어학의", word: "linguistic" },
  { meaning: "지질학", word: "geology" },
  { meaning: "토론자단, 패널 넓은 직사각형의 합판", word: "panel" },
  { meaning: "갈다, 빻다", word: "grind" },
  { meaning: "기둥", word: "pillar" },
  { meaning: "~을 잘 해 내다, 다루다", word: "manage" },
  { meaning: "가능성, 가망", word: "possibility" },
  { meaning: "조롱하다, 가짜의", word: "mock" },
  { meaning: "치료, 요법", word: "remedy" },
  { meaning: "약속, 맹세 약속하다, 맹세하다", word: "pledge" },
  { meaning: "손으로 쓰기, 대본", word: "script" },
  { meaning: "적절성, 예의 바름", word: "propriety" },
  { meaning: "형제자매, 동기", word: "sibling" },
  { meaning: "관목", word: "shrub" },
  { meaning: "유일한", word: "sole" },
  { meaning: "높이 치솟다", word: "soar" },
  { meaning: "(대학·고등학교) 2학년생", word: "sophomore" },
  { meaning: "증상", word: "symptom" },
  { meaning: "소송인, 구혼자", word: "suitor" },
  { meaning: "절제하는 (기후가) 온화한", word: "temperate" },
  { meaning: "철저한", word: "thorough" },
  { meaning: "초음파", word: "ultrasound" },
  { meaning: "수행하다, (일을)떠맡다 착수하다", word: "undertake" },
  { meaning: "비정상의", word: "abnormal" },
  { meaning: "할당하다, 배분하다", word: "allocate" },
  { meaning: "관", word: "coffin" },
  { meaning: "(공이) 튀다, 뛰어오르다", word: "bounce" },
  { meaning: "인식의, 인지력 있는", word: "cognitive" },
  { meaning: "탄소", word: "carbon" },
  { meaning: "부정한, 부패한 타락시키다", word: "corrupt" },
  { meaning: "오염시키다", word: "contaminate" },
  { meaning: "마감 시한, 최종 기한", word: "deadline" },
  { meaning: "논란, 논쟁", word: "controversy" },
  { meaning: "신성한, 신으로부터의 신이 내린", word: "divine" },
  { meaning: "편의, 편리", word: "convenience" },
  { meaning: "적도", word: "equator" },
  { meaning: "(군인을) 모집하다,  도움을 얻다", word: "enlist" },
  { meaning: "탐험(대)", word: "expedition" },
  { meaning: "외부의", word: "external" },
  { meaning: "실제의", word: "factual" },
  { meaning: "화려한, 아주 멋진", word: "gorgeous" },
  { meaning: "아첨", word: "flattery" },
  { meaning: "짐승의 떼", word: "herd" },
  { meaning: "방해하다", word: "hinder" },
  { meaning: "겸손한, 비천한", word: "humble" },
  { meaning: "운동, 움직임, 몸짓 몸짓으로 지시(신호)하다", word: "motion" },
  { meaning: "위생, 위생학", word: "hygiene" },
  { meaning: "조사하다, 탐사선", word: "probe" },
  { meaning: "투옥하다", word: "imprison" },
  { meaning: "후회하다, 한탄하다 유감, 후회", word: "regret" },
  { meaning: "~에 위치하다 (위치를) 찾아내다", word: "locate" },
  { meaning: "수입, 수익", word: "revenue" },
  { meaning: "노래 가사, 서정시,  서정적인", word: "lyric" },
  { meaning: "되살아나다", word: "revive" },
  { meaning: "특허, 특허권,  의 특허를 얻다", word: "patent" },
  { meaning: "(등받이가 없는) 걸상,  변기", word: "stool" },
  { meaning: "맥박", word: "pulse" },
  { meaning: "저장, 저장고", word: "storage" },
  { meaning: "돌진하다,  갑자기 일어나다", word: "rush" },
  { meaning: "늪지", word: "swamp" },
  { meaning: "흔적, 흔적을 쫓다", word: "trace" },
  { meaning: "미덕", word: "virtue" },
  { meaning: "다가오는", word: "upcoming" },
  { meaning: "일치하다, 일치, 협정", word: "accord" },
  { meaning: "칼날", word: "blade" },
  { meaning: "인정하다", word: "acknowledge" },
  { meaning: "~탓으로 돌리다,  비난하다, 비난, 책망", word: "blame" },
  { meaning: "~의 한가운데", word: "amid" },
  { meaning: "빌리다", word: "borrow" },
  { meaning: "도자기", word: "ceramic" },
  { meaning: "(주거 침입) 강도", word: "burglar" },
  { meaning: "보완하다, 보충물", word: "complement" },
  { meaning: "증명서", word: "certificate" },
  { meaning: "고백하다", word: "confess" },
  { meaning: "(사람들의) 무리, (과일의) 송이, 성단", word: "cluster" },
  { meaning: "나오다, 나타나다 드러나다", word: "emerge" },
  { meaning: "(업무 따위를) 실시하다 행위, 안내", word: "conduct" },
  { meaning: "추출하다, 추출물", word: "extract" },
  { meaning: "전달하다, 나르다", word: "convey" },
  { meaning: "정지, 일시 멈춤,  정지하다, 정지시키다", word: "halt" },
  { meaning: "호화로운, 사치스러운", word: "deluxe" },
  { meaning: "지옥", word: "hell" },
  { meaning: "깊이", word: "depth" },
  { meaning: "막대한", word: "immense" },
  { meaning: "끌어내다,  ~에서 비롯되다", word: "derive" },
  { meaning: "상아, 상아색", word: "ivory" },
  { meaning: "포옹, 포옹하다 받아들이다", word: "embrace" },
  { meaning: "면허, 인가 면허[인가]를 내주다", word: "license" },
  { meaning: "증발하다", word: "evaporate" },
  { meaning: "복권, 추첨", word: "lottery" },
  { meaning: "절름발이의", word: "lame" },
  { meaning: "심사숙고하다", word: "ponder" },
  { meaning: "나머지의, 남은 남은 음식", word: "leftover" },
  { meaning: "화해", word: "reconciliation" },
  { meaning: "억압하다", word: "oppress" },
  { meaning: "하수", word: "sewage" },
  { meaning: "전염병", word: "plague" },
  { meaning: "뇌졸중, 강타", word: "stroke" },
  { meaning: "반복성의", word: "repetitive" },
  { meaning: "주관적인, 주격의", word: "subjective" },
  { meaning: "신맛이 나는", word: "sour" },
  { meaning: "보증, 영장, 보증하다", word: "warrant" },
  { meaning: "이식, 이식하다", word: "transplant" },
  { meaning: "풍부한", word: "abundant" },
  { meaning: "주장하다, 행사하다", word: "assert" },
  { meaning: "고도, 높이", word: "altitude" },
  { meaning: "강당", word: "auditorium" },
  { meaning: "거만한", word: "arrogant" },
  { meaning: "꽃다발", word: "bouquet" },
  { meaning: "경매, 경매에 부치다", word: "auction" },
  { meaning: "축적", word: "buildup" },
  { meaning: "음료", word: "beverage" },
  { meaning: "정교한, 공들인", word: "elaborate" },
  { meaning: "혼합, 혼합하다", word: "blend" },
  { meaning: "먹이를 주다, 부양하다", word: "feed" },
  { meaning: "중개인", word: "broker" },
  { meaning: "반응, 피드백", word: "feedback" },
  { meaning: "아늑한", word: "cozy" },
  { meaning: "발명하다", word: "invent" },
  { meaning: "복제품, 복제하다 이중으로 하다", word: "duplicate" },
  { meaning: "(물건을) 놓다 (알을) 낳다", word: "lay" },
  { meaning: "(평판을) 얻다, 벌다", word: "earn" },
  { meaning: "(집합적) 기계", word: "machinery" },
  { meaning: "이국적인", word: "exotic" },
  { meaning: "무시하다, 소홀, 무시", word: "neglect" },
  { meaning: "흘긋 봄, 흘긋 보다 깨닫다", word: "glimpse" },
  { meaning: "강박 관념을 갖다 (사람의 마음을)사로잡다", word: "obsess" },
  { meaning: "큰 슬픔", word: "grief" },
  { meaning: "(전쟁·질병 등의) 발발,  폭동", word: "outbreak" },
  { meaning: "뛰어난, 우세한", word: "predominant" },
  { meaning: "통행인, 지나가는 사람", word: "passerby" },
  { meaning: "이성적인, 합리적인", word: "rational" },
  { meaning: "개척자, 개척자의 개척하다", word: "pioneer" },
  { meaning: "생각나게 하다 상기시키다", word: "remind" },
  { meaning: "증진하다, 승진시키다", word: "promote" },
  { meaning: "얇은 조각, 얇게 썰다", word: "slice" },
  { meaning: "방사성의", word: "radioactive" },
  { meaning: "부풀다, 팽창", word: "swell" },
  { meaning: "보유하다", word: "retain" },
  { meaning: "사라지다", word: "vanish" },
  { meaning: "던지다", word: "toss" },
  { meaning: "용사", word: "warrior" },
  { meaning: "원상태로 돌리다 (매듭을) 풀다", word: "undo" },
  { meaning: "변호사", word: "attorney" },
  { meaning: "적응시키다", word: "adapt" },
  { meaning: "시장, 바자 (중동의) 상점가", word: "bazzar" },
  { meaning: "암살하다", word: "assassinate" },
  { meaning: "타박상, 멍, 멍들게 하다 타박상을 입히다", word: "bruise" },
  { meaning: "조심하다", word: "beware" },
  { meaning: "분배하다", word: "dispense" },
  { meaning: "아슬아슬한, 숨 막히는", word: "breathtaking" },
  { meaning: "생태학", word: "ecology" },
  { meaning: "전염병, 유행병", word: "epidemic" },
  { meaning: "쫓아내다", word: "expel" },
  { meaning: "수갑", word: "handcuff" },
  { meaning: "유창한", word: "fluent" },
  { meaning: "지능, 지성", word: "intelligence" },
  { meaning: "하부구조, 뼈대, 틀", word: "framework" },
  { meaning: "장식, 장식하다", word: "ornament" },
  { meaning: "유전, 유전 형질", word: "heredity" },
  { meaning: "전복시키다, 전복", word: "overturn" },
  { meaning: "손상시키다", word: "impair" },
  { meaning: "대표 작품 선집 포트폴리오, 유가 증권", word: "portfolio" },
  { meaning: "유도하다, 설득하다", word: "induce" },
  { meaning: "~에 앞서다,  먼저 일어나다", word: "precede" },
  { meaning: "내부, 내부의", word: "interior" },
  { meaning: "임신한", word: "pregnant" },
  { meaning: "가장자리", word: "margin" },
  { meaning: "익은", word: "ripe" },
  { meaning: "은유, 은유법", word: "metaphor" },
  { meaning: "분리하다", word: "separate" },
  { meaning: "수도권의, 대도시의", word: "metropolitan" },
  { meaning: "정착하다, 정착시키다 결정하다", word: "settle" },
  { meaning: "순진한", word: "naïve" },
  { meaning: "사색하다, 투기하다", word: "speculate" },
  { meaning: "쟁기, 쟁기질하다", word: "plow" },
  { meaning: "수업료", word: "tuition" },
  { meaning: "연장하다", word: "prolong" },
  { meaning: "긴급한, 다급한", word: "ugent" },
  { meaning: "떨구다, 흘리다 발산하다", word: "shed" },
  { meaning: "증기, 증발하다", word: "vapor" },
  { meaning: "방패, 보호물, 보호하다", word: "shield" },
  { meaning: "진동하다, 흔들다", word: "vibrate" },
  { meaning: "닻, 앵커, 닻을 내리다", word: "anchor" },
  { meaning: "상승, 밀어올림,  밀어올리다, 증가하다", word: "boost" },
  { meaning: "익명의", word: "anonymous" },
  { meaning: "파묻다", word: "bury" },
  { meaning: "항생 물질", word: "antibiotic" },
  { meaning: "연민, 동정", word: "compassion" },
  { meaning: "충돌하다", word: "collide" },
  { meaning: "일관된, 모순이 없는", word: "consistent" },
  { meaning: "합성물, 합성의,  합성하다", word: "compound" },
  { meaning: "토론하다", word: "discuss" },
  { meaning: "도구, 실행하다", word: "implement" },
  { meaning: "~을 혼란에 빠뜨리다 붕괴시키다", word: "disrupt" },
  { meaning: "(숨을) 들이쉬다", word: "inhale" },
  { meaning: "총합, 총합의, 엄청난 ~의 총익을 올리다", word: "gross" },
  { meaning: "문학, 문예, 문헌", word: "literature" },
  { meaning: "체육, 체조", word: "gymnastics" },
  { meaning: "고리", word: "loop" },
  { meaning: "풀, 반죽, 풀칠하다 붙이다", word: "paste" },
  { meaning: "기념물, 기념관", word: "memorial" },
  { meaning: "몰두, 집착, 선취", word: "preoccupation" },
  { meaning: "과수원", word: "orchard" },
  { meaning: "선전 활동, 선전", word: "propaganda" },
  { meaning: "따라잡다", word: "overtake" },
  { meaning: "선동하다, 자극하다", word: "provoke" },
  { meaning: "비율, 부분", word: "proportion" },
  { meaning: "심판, 심판하다", word: "referee" },
  { meaning: "가능성, 전망", word: "prospect" },
  { meaning: "~을 닮다", word: "resemble" },
  { meaning: "인용하다", word: "quote" },
  { meaning: "녹, 녹슬다", word: "rust" },
  { meaning: "참조, 참고, 언급", word: "reference" },
  { meaning: "분야, 지역, 부채꼴", word: "sector" },
  { meaning: "소집하다, 소환하다", word: "summon" },
  { meaning: "혼자의, 외로운, 고독한", word: "solitary" },
  { meaning: "기술[기법]의, 전문적인", word: "technical" },
  { meaning: "(발목·손목 등을) 삐다", word: "sprain" },
  { meaning: "빈, 비어있는", word: "vacant" },
  { meaning: "(정처 없이) 돌아다니다 유랑, 방랑", word: "wander" },
  { meaning: "견디다", word: "withstand" },
  { meaning: "사악한", word: "wicked" },
  { meaning: "단언하다", word: "affirm" },
  { meaning: "달라붙다, 집착하다", word: "cling" },
  { meaning: "갑옷", word: "armor" },
  { meaning: "복제 생물, 클론 복제하다", word: "clone" },
  { meaning: "사랑스러운", word: "beloved" },
  { meaning: "일치하다,  서신 왕래하다", word: "correspond" },
  { meaning: "사기꾼, 갈고리 구부리다", word: "crook" },
  { meaning: "나누다, 분리하다, 분할", word: "divide" },
  { meaning: "단서, 신호", word: "cue" },
  { meaning: "진정시키다 편함, 용이함", word: "ease" },
  { meaning: "(대규모의) 요새", word: "fortress" },
  { meaning: "탐험하다", word: "explore" },
  { meaning: "가설", word: "hypothesis" },
  { meaning: "피로, 피곤하게 하다", word: "fatigue" },
  { meaning: "묻다, 조사하다", word: "inquire" },
  { meaning: "벼룩", word: "flea" },
  { meaning: "통합, (수학) 적분", word: "integration" },
  { meaning: "기금, 자금을 제공하다", word: "fund" },
  { meaning: "이동하다, 이주하다", word: "migrate" },
  { meaning: "타고난", word: "inborn" },
  { meaning: "분명치 않은, 무명의 이해하기 어려운", word: "obscure" },
  { meaning: "사마귀, 점", word: "mole" },
  { meaning: "겹치다, 중복", word: "overlap" },
  { meaning: "돌연변이, 변화", word: "mutation" },
  { meaning: "~으로 여기다 관계, 고려", word: "regard" },
  { meaning: "이상한, 홀수의", word: "odd" },
  { meaning: "마천루, 고층 건물", word: "skyscraper" },
  { meaning: "~의 껍질을 벗기다, 껍질", word: "peel" },
  { meaning: "삽", word: "spade" },
  { meaning: "예언", word: "prophecy" },
  { meaning: "광경", word: "spectacle" },
  { meaning: "흉내 내다,  모의시험을 하다", word: "simulate" },
  { meaning: "과잉, 나머지 과잉의, 나머지의", word: "surplus" },
  { meaning: "밟다, 걷다, 밟음", word: "tread" },
  { meaning: "관세, 관세를 부과하다", word: "tariff" },
  { meaning: "폭군, 전제 군주", word: "tyrant" },
  { meaning: "진공, 진공청소기 진공청소기로 청소하다", word: "vacuum" },
  { meaning: "백신, (컴퓨터) 바이러스 예방 프로그램", word: "vaccine" },
  { meaning: "효모, 발효하다", word: "yeast" },
  { meaning: "토하다", word: "vomit" },
  { meaning: "묶음, 꾸러미", word: "bundle" },
  { meaning: "거스르는, 반대의,  부정적인", word: "adverse" },
  { meaning: "섭씨의, 섭씨", word: "Celsius" },
  { meaning: "이해하다, 감상하다 고맙게 생각하다", word: "appreciate" },
  { meaning: "죄다, 위축시키다", word: "constrict" },
  { meaning: "수로, 운하", word: "canal" },
  { meaning: "동봉하다, 에워싸다", word: "enclose" },
  { meaning: "검열", word: "censorship" },
  { meaning: "밀가루", word: "flour" },
  { meaning: "껍질, 지각", word: "crust" },
  { meaning: "의복", word: "garment" },
  { meaning: "저주, 저주하다", word: "curse" },
  { meaning: "삽입하다", word: "insert" },
  { meaning: "행위, 업적", word: "deed" },
  { meaning: "교환, 교차점(I.C.) 교환하다", word: "interchange" },
  { meaning: "(타국으로) 이주하다", word: "emigrate" },
  { meaning: "아주 흥미로운", word: "intriguing" },
  { meaning: "결점, 흠", word: "flaw" },
  { meaning: "직관적인, 직관에 의한", word: "intuitive" },
  { meaning: "이마", word: "forehead" },
  { meaning: "날카로운, 예민한", word: "keen" },
  { meaning: "석쇠, 석쇠로 굽다 심문하다", word: "grill" },
  { meaning: "측량, 측정, 치수", word: "measurement" },
  { meaning: "피할 수 없는", word: "inevitable" },
  { meaning: "시작되다, 비롯하다", word: "originate" },
  { meaning: "조종하다, 조작하다", word: "manipulate" },
  { meaning: "애국자", word: "patriot" },
  { meaning: "조언자", word: "mentor" },
  { meaning: "평판, 명성", word: "reputation" },
  { meaning: "더러운, 불쾌한", word: "nasty" },
  { meaning: "억제하다, 구속하다", word: "restrain" },
  { meaning: "목초지, 목장", word: "pasture" },
  { meaning: "자발적인,  자연히 일어나는", word: "spontaneous" },
  { meaning: "뛰어들다, 던져 넣다", word: "plunge" },
  { meaning: "복종시키다, 복종하다, 제출하다", word: "submit" },
  { meaning: "피골이 상접한, 마른", word: "skinny" },
  { meaning: "검증하다, 증명하다 증언하다", word: "testify" },
  { meaning: "생생한", word: "vivid" },
  { meaning: "수직의", word: "vertical" },
  { meaning: "손목", word: "wrist" },
  { meaning: "알레르기", word: "allergy" },
  { meaning: "유산하다, 낙태하다 실패하다, 중단되다", word: "abort" },
  { meaning: "공동묘지", word: "cemetery" },
  { meaning: "저음, 베이스", word: "bass" },
  { meaning: "연속적인, 일관된", word: "consecutive" },
  { meaning: "마차, 탈 것", word: "carriage" },
  { meaning: "숙고하다, 응시하다", word: "contemplate" },
  { meaning: "만성적인, 장기간의", word: "chronic" },
  { meaning: "졸리는", word: "drowsy" },
  { meaning: "기념하다", word: "commemorate" },
  { meaning: "염료, 염색하다", word: "dye" },
  { meaning: "압축하다", word: "compress" },
  { meaning: "노력, 노력하다", word: "endeavor" },
  { meaning: "지정하다, 가리키다", word: "designate" },
  { meaning: "세우다, 똑바로 선", word: "erect" },
  { meaning: "과장하다 과장해서 말하다", word: "exaggerate" },
  { meaning: "여성의, 여성스러운", word: "feminine" },
  { meaning: "벌금, 박탈, 몰수 박탈당하다", word: "forfeit" },
  { meaning: "기초, 토대, 재단", word: "foundation" },
  { meaning: "다스리다", word: "govern" },
  { meaning: "관개(물 대는 시설)", word: "irrigation" },
  { meaning: "검사하다, 점검하다", word: "inspect" },
  { meaning: "외향적인", word: "outgoing" },
  { meaning: "강렬한", word: "intense" },
  { meaning: "피난, 피난처, 위안", word: "refuge" },
  { meaning: "원시의, 초기의, 미개의 원시인", word: "primitive" },
  { meaning: "수수께끼", word: "riddle" },
  { meaning: " 무작위의, 임의의", word: "random" },
  { meaning: "인종 차별, 분리", word: "segregation" },
  { meaning: "추천하다", word: "recommend" },
  { meaning: "반도체", word: "semiconductor" },
  { meaning: "순서, 결과, 연속", word: "sequence" },
  { meaning: "자극하다, 고무하다", word: "stimulate" },
  { meaning: "산산이 부서지다, 파편", word: "shatter" },
  { meaning: "표면상의, 피상적인", word: "superficial" },
  { meaning: "(자판기등)투입 구멍 가늘고 길쭉한 구멍", word: "slot" },
  { meaning: "맹세하다, 욕하다", word: "swear" },
  { meaning: "가파른, 경사가 급한", word: "steep" },
  { meaning: "밑에 놓인,  기초를 이루는", word: "underlying" },
  { meaning: "유독한, 중독의", word: "toxic" },
  { meaning: "식욕", word: "appetite" },
  { meaning: "편견", word: "bias" },
  { meaning: "달성하다", word: "attain" },
  { meaning: "비약적인 발전, 돌파구 획기적 발전", word: "breakthrough" },
  { meaning: "진짜의, 진정한", word: "authentic" },
  { meaning: "동의, 허락, 동의하다", word: "consent" },
  { meaning: "소유물, 소지품", word: "belonging" },
  { meaning: "조정하다, 동등한", word: "coordinate" },
  { meaning: "혼돈, 무질서", word: "chaos" },
  { meaning: "부족한, 불완전한", word: "deficient" },
  { meaning: "강요하다, ~하게 만들다", word: "compel" },
  { meaning: "동등한, 상당하는", word: "equivalent" },
  { meaning: "집행의, 경영의 임원, 경영진", word: "executive" },
  { meaning: "베틀, 불쑥 나타나다", word: "loom" },
  { meaning: "함축, 암시", word: "implication" },
  { meaning: "협상하다", word: "negotiate" },
  { meaning: "내키게 하다, 기울이다 경사", word: "incline" },
  { meaning: "귀찮은 사람, 성가신 것", word: "nuisance" },
  { meaning: "지수, 색인", word: "index" },
  { meaning: "고아", word: "orphan" },
  { meaning: "솜씨, 독창력", word: "ingenuity" },
  { meaning: "금지하다, 무효화하다 무법자", word: "outlaw" },
  { meaning: "천부적인, 본질적인", word: "innate" },
  { meaning: "미리 보기, 예고편,  시사회", word: "preview" },
  { meaning: "언급하다, 언급", word: "mention" },
  { meaning: "특권, 특권을 주다", word: "privilege" },
  { meaning: "현미경", word: "microscope" },
  { meaning: "지방, (행정구역)도, 분야", word: "province" },
  { meaning: "다수의, 수많은", word: "numerous" },
  { meaning: "자주색, 자주색의", word: "purple" },
  { meaning: "진행, 진행 중의", word: "ongoing" },
  { meaning: "기록하다, 녹음하다 기록, 증언", word: "record" },
  { meaning: "(정서·지능·학력) 발달이 뒤진", word: "retarded" },
  { meaning: "야만스런, 잔인한 야만인", word: "savage" },
  { meaning: "떨림, 떨다", word: "shiver" },
  { meaning: "나사, 나사로 고정하다", word: "screw" },
  { meaning: "변천, 과도기", word: "transition" },
  { meaning: "잡다, 이해하다", word: "seize" },
  { meaning: "취약한, 상처 입기 쉬운", word: "vulnerable" },
  { meaning: "짜내다", word: "squeeze" },
  { meaning: "감탄하다, 존경하다", word: "admire" },
  { meaning: "아는 사이, 교제", word: "acquaintance" },
  { meaning: "미학", word: "aesthetics" },
  { meaning: "~할 여유가 있다", word: "afford" },
  { meaning: "상호 관계, 상호 관련", word: "correlation" },
  { meaning: "돕다, 도움, 조력", word: "aid" },
  { meaning: "속이다", word: "deceive" },
  { meaning: "확대하다, 증폭시키다", word: "amplify" },
  { meaning: "불구로 만들다,  <물리> 변형시키다", word: "deform" },
  { meaning: "투표, 투표용지,  투표하다", word: "ballot" },
  { meaning: "고갈시키다, 격감시키다", word: "deplete" },
  { meaning: "불다, 바람에 날리다", word: "blow" },
  { meaning: "진지함, 진심", word: "earnest" },
  { meaning: "무뚝뚝한, 퉁명스러운 무딘, 둔감한", word: "blunt" },
  { meaning: "기업, 사업", word: "enterprise" },
  { meaning: "끓다, 삶다", word: "boil" },
  { meaning: "거대함, 중요성 (지진) 진도", word: "magnitude" },
  { meaning: "터뜨리다, 파열, 폭발", word: "burst" },
  { meaning: "역설, 패러독스", word: "paradox" },
  { meaning: "내던지다, (빛을) 발하다", word: "cast" },
  { meaning: "철학", word: "philosophy" },
  { meaning: "협력하다", word: "collaborate" },
  { meaning: "옆 얼굴, 인물 소개", word: "profile" },
  { meaning: "부정하다, 반박하다 모순되다", word: "contradict" },
  { meaning: "조리법, 비법", word: "recipe" },
  { meaning: "부할, 나누기, (군대)사단 (대학의) 학부", word: "division" },
  { meaning: "도살하다, 도살, 대학살", word: "slaughter" },
  { meaning: "잘못을 입증하다", word: "falsify" },
  { meaning: "연속되는, 상속의", word: "successive" },
  { meaning: "노, 노를 젖다", word: "paddle" },
  { meaning: "능가하다", word: "surpass" },
  { meaning: "초능력이 있는 초자연적인, 무당, 영매", word: "psychic" },
  { meaning: "넘겨주다, 항복하다 포기하다", word: "surrender" },
  { meaning: "전력질주, 단거리 경주 전력질주하다", word: "sprint" },
  { meaning: "휩쓸다, 청소하다", word: "sweep" },
  { meaning: "서 있는 자세, 태도", word: "stance" },
  { meaning: "스릴, 전율 감동(흥분)시키다", word: "thrill" },
  { meaning: "팽팽한, 긴장한 긴장시키다", word: "tense" },
  { meaning: "떨다", word: "tremble" },
  { meaning: "목재", word: "timber" },
  { meaning: "동맥, 간선 도로", word: "artery" },
  { meaning: "가속하다, 촉진하다", word: "accelerate" },
  { meaning: "말하다, 명령하다 입찰하다, 입찰", word: "bid" },
  { meaning: "열망하다, 동경하다", word: "aspire" },
  { meaning: "혼합물, 퇴비", word: "compost" },
  { meaning: "카탈로그, (물품·책)목록", word: "catalog" },
  { meaning: "충돌하다, 투쟁, 충돌", word: "conflict" },
  { meaning: "함축, 내포", word: "connotation" },
  { meaning: "화장품, 미용의", word: "cosmetic" },
  { meaning: "(암호를) 해독하다", word: "decode" },
  { meaning: "개몽, 개화, 깨달음", word: "enlightenment" },
  { meaning: "영역, 영토, 분야", word: "domain" },
  { meaning: "불의, 열렬한, 불같은", word: "fiery" },
  { meaning: "연극의, 극적인", word: "dramatic" },
  { meaning: "상냥한, 우아한", word: "gracious" },
  { meaning: "사나이, 동료, 동료의", word: "fellow" },
  { meaning: "괴롭히다, 희롱하다 침략하다", word: "harass" },
  { meaning: "일사병, 열사병", word: "heatstroke" },
  { meaning: "집들이", word: "housewarming" },
  { meaning: "불가분의 떼어 낼 수 없는", word: "inseparable" },
  { meaning: "명령하다, 위임하다", word: "mandate" },
  { meaning: "막다, 방해하다", word: "obstruct" },
  { meaning: "갈기갈기 찢다, 째다", word: "shred" },
  { meaning: "달걀 모양의, 타원의 타원체", word: "oval" },
  { meaning: "빈민가", word: "slum" },
  { meaning: "순찰, 순찰병, 순찰하다", word: "patrol" },
  { meaning: "세련된, 정교한", word: "sophisticated" },
  { meaning: "죽다, 소멸하다", word: "perish" },
  { meaning: "대못, 대못을 박다", word: "spike" },
  { meaning: "살금살금 움직이다 몰래 움직이다", word: "sneak" },
  { meaning: "조종하다, 인도하다", word: "steer" },
  { meaning: "정치가", word: "statesman" },
  { meaning: "기질, 성질", word: "temperament" },
  { meaning: "인습, 고정관념 연판 인쇄", word: "stereotype" },
  { meaning: "증정물, 진상품, 조세 감사[존경]의 표시", word: "tribute" },
  { meaning: "채식주의자, 채식의 채식주의자의", word: "vegetarian" },
  { meaning: "예측할 수 없는", word: "unpredictable" },
  { meaning: "경험이 많은, 퇴역 군인 베테랑", word: "veteran" },
  { meaning: "말의, 구두의", word: "verbal" },
  { meaning: "직업, 천직", word: "vocation" },
  { meaning: "신청자, 지원자", word: "applicant" },
  { meaning: "타협하다, 타협", word: "compromise" },
  { meaning: "앞치마", word: "apron" },
  { meaning: "검사하다, 진찰하다", word: "examine" },
  { meaning: "오류를 증명하다,  논박하다", word: "disprove" },
  { meaning: "주요한, 으뜸가는", word: "foremost" },
  { meaning: "방해하다, 어지럽히다 혼란케하다", word: "disturb" },
  { meaning: "법인회사로 만들다 통합시키다", word: "incorporate" },
  { meaning: "탄력있는, 융통성 있는", word: "elastic" },
  { meaning: "주사하다, 도입하다", word: "inject" },
  { meaning: "반구체 (지구·천제의) 반구", word: "hemisphere" },
  { meaning: "유혹하다, 매력", word: "lure" },
  { meaning: "속이 빈, 오목한,  움푹한 곳", word: "hollow" },
  { meaning: "사기, 의욕", word: "morale" },
  { meaning: "밝게 비추다, 설명하다 계몽하다", word: "illuminate" },
  { meaning: "의무, 계약, 채무", word: "obligation" },
  { meaning: "나중 쪽의, 후자의", word: "latter" },
  { meaning: "엿보다, 엿보기", word: "peep" },
  { meaning: "모방하다, 모조의 흉내를 잘내는", word: "mimic" },
  { meaning: "해충, 역병, 귀찮은 것", word: "pest" },
  { meaning: "저당, 주택융자", word: "mortgage" },
  { meaning: "조심, 예방 조치", word: "precaution" },
  { meaning: "반역자, 반역을 일으키다", word: "rebel" },
  { meaning: "정권, 제도", word: "regime" },
  { meaning: "재발하다, 되풀이하다", word: "recur" },
  { meaning: "종교(상)의, 종교적인", word: "religious" },
  { meaning: "성인", word: "saint" },
  { meaning: "정복하다, 진압하다 완화하다", word: "subdue" },
  { meaning: "누추한, 초라한", word: "shabby" },
  { meaning: "자살", word: "suicide" },
  { meaning: "떨다, 몸서리치다", word: "shudder" },
  { meaning: "흔들림, 흔들리다", word: "sway" },
  { meaning: "성큼성큼 걷다, 발전 성금성큼 걷기, 진보", word: "stride" },
  { meaning: "끝내다, 종결짓다", word: "terminate" },
  { meaning: "완고한, 고집이 센", word: "stubborn" },
  { meaning: "도둑질, <야구>도루", word: "theft" },
  { meaning: "발굴하다, 발견하다", word: "unearth" },
  { meaning: "고문, 고문하다", word: "torture" },
  { meaning: "울부짖다", word: "wail" },
  {
    meaning: "(경제적·사회적) 권리가 적은, 혜택 받지 못한",
    word: "underprivileged",
  },
  { meaning: "수정하다, 고치다", word: "amend" },
  { meaning: "이타주의", word: "altruism" },
  { meaning: "자치, 자율", word: "autonomy" },
  { meaning: "유추, 비슷함", word: "analogy" },
  { meaning: "짐, 부담,  ~에게 짐을 지우다", word: "burden" },
  { meaning: "인류학", word: "anthropology" },
  { meaning: "일깨우다, 불러내다", word: "evoke" },
  { meaning: "가슴", word: "breast" },
  { meaning: "민속, 민속 신앙, 신화", word: "folklore" },
  { meaning: "방어하다, 수비하다", word: "defend" },
  { meaning: "마찰, 의견 충돌", word: "friction" },
  { meaning: "둘의, 이중의", word: "dual" },
  { meaning: "<지리>위도, 위선", word: "latitude" },
  { meaning: "태평스러운, 안이한", word: "easygoing" },
  { meaning: "어머니의, 모국어의 모계의", word: "maternal" },
  { meaning: "섬유(질)", word: "fiber" },
  { meaning: "한편, 그 동안에", word: "meanwhile" },
  { meaning: "사기, 속임, 사기꾼", word: "fraud" },
  { meaning: "슬퍼하다, 애도하다", word: "mourn" },
  { meaning: "불면증", word: "insomnia" },
  { meaning: "용품, 의복 공급하다, 준비하다", word: "outfit" },
  { meaning: "중간의, 중간물", word: "intermediate" },
  { meaning: "진통제", word: "painkiller" },
  { meaning: "반어법, 아이러니", word: "irony" },
  { meaning: "헝겊 조각, 좁은 땅 헝겊 조각을 붙이다", word: "patch" },
  { meaning: "중세의", word: "medieval" },
  { meaning: "약국, 약학", word: "pharmacy" },
  { meaning: "패러다임, 이론적 틀", word: "paradigm" },
  { meaning: "예비의, 임시의,  예선, 사전준비", word: "preliminary" },
  { meaning: "조숙한, 조산한, 시기 상조의", word: "premature" },
  { meaning: "명성이 있는, 고급의 일류의", word: "prestigious" },
  { meaning: "잡아채다, 날치기하다", word: "snatch" },
  { meaning: "휴식, 휴업, 구석진 곳", word: "recess" },
  { meaning: "관객, 구경꾼", word: "spectator" },
  { meaning: "피난하다, 보호하다 피난처", word: "shelter" },
  {
    meaning: "(장소)도처에, 곳곳에,  (시간)처음부터 끝까지",
    word: "throughout",
  },
  { meaning: "잡아 늘리다, 신축성", word: "stretch" },
  { meaning: "수송[운송]하다, 수송", word: "transport" },
  { meaning: "막대한, 방대한", word: "vast" },
  { meaning: "마음이 상한, 엉망인 뒤엎다, 전복, 혼란", word: "upset" },
  { meaning: "귀여운, 사랑스러운", word: "adorable" },
  { meaning: "(수량 등이)~에 가까워지다, 대략의", word: "approximate" },
  { meaning: "나아가게 하다, 전진 진척시키다, 증진", word: "advance" },
  { meaning: "비버, 근면한 사람", word: "beaver" },
  { meaning: "(스스로) 만족해 하는 현실에 안주하는", word: "complacent" },
  { meaning: "어색한, 서투른", word: "clumsy" },
  { meaning: "침착, 평정", word: "composure" },
  { meaning: "포함하다, 구성하다", word: "comprise" },
  { meaning: "빗나가다, 비끼다, 막다", word: "deflect" },
  { meaning: "바삭바삭한 부서지기 쉬운", word: "crispy" },
  { meaning: "지속, 지속 기간", word: "duration" },
  { meaning: "가냘픈, 연약한", word: "feeble" },
  { meaning: "명백한, 분명한", word: "explicit" },
  { meaning: "교장", word: "headmaster" },
  { meaning: "검소한, 절약하는", word: "frugal" },
  { meaning: "인류, 인간성, 인간애", word: "humanity" },
  { meaning: "제국의, 황제의", word: "imperial" },
  { meaning: "죽을 운명의, 치명적인", word: "mortal" },
  { meaning: "불치의, 구제 불능의 불치 환자", word: "incurable" },
  { meaning: "평행의, 평행선 ~에 필적하는 것", word: "parallel" },
  { meaning: "탐닉하다, 만족시키다 버릇없이 기르다", word: "indulge" },
  { meaning: "후원자, 단골 손님, 고객", word: "patron" },
  { meaning: "숨다, 잠복하다", word: "lurk" },
  { meaning: "가짜의, 가짜, 사기꾼", word: "phony" },
  { meaning: "명백하게 하다, 증명하다 명백한", word: "manifest" },
  { meaning: "쓰레기, 폐기물", word: "rubbish" },
  { meaning: "목초지, 초원", word: "meadow" },
  { meaning: "비꼬는, 풍자적인", word: "sarcastic" },
  { meaning: "(실제의) 이야기, 서술 이야기의", word: "narrative" },
  { meaning: "배우자", word: "spouse" },
  { meaning: "거주시키다", word: "populate" },
  { meaning: "그 후의 ~에 이어 일어나는", word: "subsequent" },
  { meaning: "복수, 복수하다", word: "revenge" },
  { meaning: "지역, 지형, 분야, 범위", word: "terrain" },
  { meaning: "선전 문구, 슬로건", word: "slogan" },
  { meaning: "직물의, 방직의, 직물", word: "textile" },
  { meaning: "견고한, 강건한", word: "sturdy" },
  { meaning: "사용세, 통행료 요금으로 징수하다", word: "toll" },
  { meaning: "모험하다, 모험", word: "venture" },
  { meaning: "전쟁, 교전상태", word: "warfare" },
  { meaning: "장치, 기구, 조직", word: "apparatus" },
  { meaning: "일부러~하다, 괴롭히다", word: "bother" },
  { meaning: "가장자리, 국경 접하다", word: "border" },
  { meaning: "뇌물, 뇌물을 주다", word: "bribe" },
  { meaning: "여행자/순례자 무리,  (사막의) 대상", word: "caravan" },
  { meaning: "채우다,  요금을 청구하다", word: "charge" },
  { meaning: "집합적인, 집단적인 집단", word: "collective" },
  { meaning: "중화시키다, 약화시키다", word: "counteract" },
  { meaning: "양립할 수 없는 모순이 없는", word: "compatible" },
  { meaning: "진퇴양난, 딜레마, 궁지", word: "dilemma" },
  { meaning: "농축하다, 요약하다", word: "condense" },
  { meaning: "강연, 담화", word: "discourse" },
  { meaning: "셀 수 없는, 무수한", word: "countless" },
  { meaning: "고민, 고통, ~을 괴롭히다", word: "distress" },
  { meaning: "멍한 상태, 멍하게 하다", word: "daze" },
  { meaning: "직접, 바로, 직업의", word: "firsthand" },
  { meaning: "혐오하다, 미워하다", word: "detest" },
  { meaning: "필수 불가결한 없어서는 안 될 것", word: "indispensable" },
  { meaning: "문하생, 제자", word: "disciple" },
  { meaning: "잘 처리하다, 저글링하다", word: "juggle" },
  { meaning: "국경, 국경의, 최첨단의", word: "frontier" },
  { meaning: "육아실, 탁아소, 양성소", word: "nursery" },
  { meaning: "돌풍, 질풍", word: "gust" },
  { meaning: "(병적인) 비만, 비대", word: "obesity" },
  { meaning: "싸락눈, 우박 우박이 내리다", word: "hail" },
  { meaning: "땀, 노력", word: "perspiration" },
  { meaning: "균형을 잡다 균형, 평정", word: "poise" },
  { meaning: "~이 되게 하다,  주다, 표현하다", word: "render" },
  { meaning: "(관찰·활동의)범위, 시야, 조사하다", word: "scope" },
  { meaning: "보유, 기억(력)", word: "retention" },
  { meaning: "마구간, 우리, 핑계 핑계를 대다", word: "stall" },
  { meaning: "보안관", word: "sheriff" },
  { meaning: "뚱뚱한, (옷 등이)튼튼한", word: "stout" },
  { meaning: "정적인, 고정된", word: "static" },
  { meaning: "피나는, 격렬한", word: "strenuous" },
  { meaning: "구조(상)의, 조직(상)의", word: "structural" },
  { meaning: "판결, 결정", word: "verdict" },
  { meaning: "용감한, 용맹스런", word: "valiant" },
  { meaning: "억누르다, 억제하다 보류하다", word: "withhold" },
  { meaning: "허영심, 허무함", word: "vanity" },
  { meaning: "옹호자, 지지자,  지지하다", word: "advocate" },
  { meaning: "활발한, 번창하는 상쾌한", word: "brisk" },
  { meaning: "상승, 오름", word: "ascent" },
  { meaning: "강제, 압박, 거북스러움", word: "constraint" },
  { meaning: "얼굴을 붉히다 부끄러워하다", word: "blush" },
  { meaning: "전염성의, 감염성의", word: "contagious" },
  { meaning: "명백히 하다", word: "clarify" },
  { meaning: "선언하다", word: "declare" },
  { meaning: "기다, (덩굴 등)얽히다 포복, 서행", word: "creep" },
  { meaning: "법령, 포고하다", word: "decree" },
  { meaning: "(독특한) 요리, 요리법", word: "cuisine" },
  { meaning: "탈수하다, 건조시키다", word: "dehydrate" },
  { meaning: "경작하다, 양성하다 계발하다", word: "cultivate" },
  { meaning: "속이다, 착가하게하다", word: "delude" },
  { meaning: "감히~하다", word: "dare" },
  { meaning: "변경, 일탈", word: "deviation" },
  { meaning: "약화, (가치의) 하락", word: "deterioration" },
  { meaning: "식별하다, 분별하다,  ~을 인식하다", word: "discern" },
  { meaning: "혐오감, 역겹게 하다", word: "disgust" },
  { meaning: "망명, 망명자 망명시키다", word: "exile" },
  { meaning: "용해하다, 해산하다 해소하다", word: "dissolve" },
  { meaning: "내던지다, 돌진하다", word: "fling" },
  { meaning: "에워싸다, 둘러싸다", word: "encircle" },
  { meaning: "다루다", word: "handle" },
  { meaning: "평형, 균형상태", word: "equilibrium" },
  { meaning: "가려움, 가렵다 (~하고 싶어) 못 견디다", word: "itch" },
  { meaning: "일부분, 부서진 조각", word: "fragment" },
  { meaning: "물질대사, 신진대사", word: "metabolism" },
  { meaning: "사이에 끼어들다,  개입하다, 방해하다", word: "intervene" },
  { meaning: "널리 알려짐, 명성, 선전 광고", word: "publicity" },
  { meaning: "문지기, 관리인, 잡역부", word: "janitor" },
  { meaning: "비난, 비난하다", word: "reproach" },
  { meaning: "유목민, 방랑자", word: "nomad" },
  { meaning: "계획, 음모, 계획하다", word: "scheme" },
  { meaning: "개념, 의견", word: "notion" },
  { meaning: "자극, 고무, 박차를 가하다", word: "spur" },
  { meaning: "감독하다, 감시하다", word: "oversee" },
  { meaning: "만장일치의, 합의의", word: "unanimous" },
  { meaning: "용해력이 있는, 용제 지불 능력이 있는", word: "solvent" },
  { meaning: "~의 아래에, 밑에", word: "underneath" },
  { meaning: "천식", word: "asthma" },
  { meaning: "크기, 부피, 대부분", word: "bulk" },
  { meaning: "비행하다,  (비행기를) 조정하다", word: "aviate" },
  { meaning: "공존하다", word: "coexist" },
  { meaning: "대참사, 큰 재앙", word: "catastrophe" },
  { meaning: "위로하다", word: "console" },
  { meaning: "파견하다, 사절, 대표", word: "delegate" },
  { meaning: "~을 불구로 만들다 지체 부자유자", word: "cripple" },
  { meaning: "선출하다", word: "elect" },
  { meaning: "냉소적인, 비꼬는", word: "cynical" },
  { meaning: "공감하다,  감정 이입을 하다", word: "empathize" },
  { meaning: "경멸하다", word: "despise" },
  { meaning: "(힘·지식 등을) 쓰다,  발휘하다", word: "exert" },
  { meaning: "분별 있는, 사려 깊은", word: "discreet" },
  { meaning: "실험, 실험하다", word: "experiment" },
  { meaning: "논쟁, 분쟁, 토의하다", word: "dispute" },
  { meaning: "전문 지식[기술]", word: "expertise" },
  { meaning: "문제점, 장애", word: "drawback" },
  { meaning: "본부(단수취급)", word: "headquarters" },
  { meaning: "공포, 무서워하다", word: "dread" },
  { meaning: "선천적인, 본래의", word: "inherent" },
  { meaning: "열중하게 하다 ", word: "engross" },
  { meaning: "간격, 틈", word: "interval" },
  { meaning: "소유지, 재산", word: "estate" },
  { meaning: "계속하다, 끈기", word: "last" },
  { meaning: "환대, 후한 대접", word: "hospitality" },
  { meaning: "~을 꼬집다, 집다, 괴롭히다", word: "pinch" },
  { meaning: "손으로 쓴 것, 원고 필사본", word: "manuscript" },
  { meaning: "시간을 지키는, 기한을 지키는", word: "punctual" },
  { meaning: "왕국, 영역", word: "realm" },
  { meaning: "직사각형의, 직각의", word: "rectangular" },
  { meaning: "꾸짖다, 책망하다", word: "reprove" },
  { meaning: "~을 새롭게 하다, 수리하다", word: "renovate" },
  { meaning: "부분, 분할하다", word: "segment" },
  { meaning: "반박, 말대꾸, 반박하다, 말대꾸하다", word: "retort" },
  { meaning: "더미, 쌓아올림, 쌓다 (도서관의) 서가, 쌓이다", word: "stack" },
  { meaning: "가시, 괴로움의 원인", word: "thorn" },
  { meaning: "방안, 전술", word: "tactics" },
  { meaning: "렌치(너트를 죄는 기구), 비틀기, 비틀다, 빠다", word: "wrench" },
  { meaning: "검증하다, 입증하다", word: "verify" },
  { meaning: "수용하다, 숙박시키다", word: "accommodate" },
  { meaning: "극도의 피로,  쇠진, 연소 종료", word: "burnout" },
  { meaning: "통, (석유) 1배럴", word: "barrel" },
  { meaning: "수로, 도랑", word: "ditch" },
  { meaning: "야만적인, 짐승 같은 잔혹한", word: "brutal" },
  { meaning: "쫓아내다, 배출하다", word: "eject" },
  { meaning: "우회하다, 우회로", word: "bypass" },
  { meaning: "적격의, 적임자", word: "eligible" },
  { meaning: "세제", word: "detergent" },
  { meaning: "법제화하다, 제정하다", word: "enact" },
  { meaning: "웅변의, 표현이 풍부한", word: "eloquent" },
  { meaning: "교차(로), 횡당", word: "intersection" },
  { meaning: "연기, 연기 나다", word: "fume" },
  { meaning: "산사태, 압도적인 승리", word: "landslide" },
  { meaning: "(필요한 것을)제공하다, 갖추다", word: "furnish" },
  { meaning: "유산", word: "legacy" },
  { meaning: "위험한, 모험적인", word: "hazardous" },
  { meaning: "직선의, 길이의,  1차(원)의", word: "linear" },
  { meaning: "가장 깊숙한, 가장 깊숙한 부분", word: "innermost" },
  { meaning: "우울한, 우울함", word: "melancholy" },
  { meaning: "목사, 정교 지도자", word: "pastor" },
  { meaning: "단조로운, 지루한", word: "monotonous" },
  { meaning: "앞서 있었던 것 선배, 전임자", word: "predecessor" },
  { meaning: "영구의, 끊임없는", word: "perpetual" },
  { meaning: "선사 시대의", word: "prehistoric" },
  { meaning: "그럴듯한, 말재주 있는", word: "plausible" },
  { meaning: "선언하다, 증명하다", word: "proclaim" },
  { meaning: "주최자, 사회자", word: "presider" },
  { meaning: "빠른, 신속한", word: "rapid" },
  { meaning: "탐색, 탐구", word: "quest" },
  { meaning: "발진, 뾰루지, 성급한 무분별한", word: "rash" },
  { meaning: "거주하다", word: "reside" },
  { meaning: "존경, 숭배", word: "reverence" },
  { meaning: "질질 끌며 걷다, 뒤섞다", word: "shuffle" },
  { meaning: "두개골", word: "skull" },
  { meaning: "간단, 단순, 소박", word: "simplicity" },
  { meaning: "주요한, 주요 산물", word: "staple" },
  { meaning: "요약하다", word: "summarize" },
  { meaning: "하급의, 부차적인, 하급자, 경시하다", word: "subordinate" },
  { meaning: "재치, 기지", word: "tact" },
  { meaning: "압도하다, 극복하다", word: "overcome" },
  { meaning: "적대자, 라이벌", word: "antagonist" },
  { meaning: "확신, 유죄 판결", word: "conviction" },
  { meaning: "귀의, 청각의", word: "auditory" },
  { meaning: "물리치다, 무시하다 공공연히 반항하다", word: "defy" },
  { meaning: "세계적인, 세계주의의 세계인, 국제인", word: "cosmopolitan" },
  { meaning: "퇴보하다, 타락하다", word: "degenerate" },
  { meaning: "신념, (종교의) 교의 ", word: "creed" },
  { meaning: "파괴하다, 폐지하다", word: "demolish" },
  { meaning: "떼어내다, 분리하다", word: "detach" },
  { meaning: "땅거미, 어스름", word: "dusk" },
  { meaning: "깊숙이 박다,  깊이 간직하다", word: "embed" },
  { meaning: "외적인, 외부의", word: "extrinsic" },
  { meaning: "매혹하다,  ~에 마법을 걸다", word: "enchant" },
  { meaning: "광란의, 미친", word: "frantic" },
  { meaning: "참다, 인내하다, 견디다", word: "endure" },
  { meaning: "(집합적) 상품", word: "merchandise" },
  { meaning: "위업, 공적", word: "feat" },
  { meaning: "합병하다, 차차 변하다", word: "merge" },
  { meaning: "고정시키다", word: "fixate" },
  { meaning: "신음, 신음하다, 불평하다", word: "moan" },
  { meaning: "잘못 두다", word: "misplace" },
  { meaning: "자식, 새끼, 성과", word: "offspring" },
  { meaning: "선교사", word: "missionary" },
  { meaning: "(벽 따위에) 붙이다, 우편", word: "post" },
  { meaning: "복합적인, 다수의 (수학) 배수", word: "multiple" },
  { meaning: "세다, 계산하다,  생각하다", word: "reckon" },
  { meaning: "육식동물, 약탈자 포식자", word: "predator" },
  { meaning: "임대하다, 집세", word: "rent" },
  { meaning: "나아가게 하다,  추진하다", word: "propel" },
  { meaning: "각각, 저마다", word: "respectively" },
  { meaning: "(빛, 소리) 굴절", word: "refraction" },
  { meaning: "감상, 정서", word: "sentiment" },
  { meaning: "파충류", word: "reptile" },
  { meaning: "지탱하다, 유지하다", word: "sustain" },
  { meaning: "중고의, 간접적인", word: "secondhand" },
  { meaning: "(일·문제를) 다루다,  도구, (축구의) 태클", word: "tackle" },
  { meaning: "밀다, 밀치다", word: "thrust" },
  { meaning: "그리워하다, 열망하다", word: "yearn" },
  { meaning: "가정용품, 기구, 용구", word: "utensil" },
  { meaning: "구획, 칸막이", word: "compartment" },
  { meaning: "애매모호한 두 가지로 해석 가능한", word: "ambiguous" },
  { meaning: "위축되다, 굽실거리다", word: "cringe" },
  { meaning: "파산", word: "bankruptcy" },
  { meaning: "불평, 불평하다,  으르렁거리다", word: "grumble" },
  { meaning: "맨발의, 맨발로", word: "barefoot" },
  { meaning: "혼합, 잡종", word: "hybrid" },
  { meaning: "반격. 역습,  반겨하다, 역습하다", word: "counterattack" },
  { meaning: "취임의, 취임사", word: "inaugural" },
  { meaning: "누적되는, 점증적인", word: "cumulative" },
  { meaning: "정신이상의, 비상식적인", word: "insane" },
  { meaning: "분리된, 별개의", word: "discrete" },
  { meaning: "농담, 조롱", word: "jest" },
  { meaning: "결투", word: "duel" },
  { meaning: "유괴, 납치하다", word: "kidnap" },
  { meaning: "열광, 열정, 열의", word: "enthusiasm" },
  { meaning: "책임을 져야 할,  ~할 것 같은,~하기 쉬운", word: "liable" },
  { meaning: "원한, 유감", word: "grudge" },
  { meaning: "사지, 팔다리", word: "limb" },
  { meaning: "줄(이)다", word: "lessen" },
  { meaning: "얌전한, 온순한", word: "meek" },
  { meaning: "상, 면, 양상, 단계", word: "phase" },
  { meaning: "주목할 만한", word: "notable" },
  { meaning: "번영하다, 번창하다", word: "prosper" },
  { meaning: "착수, 시작", word: "outset" },
  { meaning: "신중한, 빈틈없는", word: "prudent" },
  { meaning: "침투하다, 꿰뚫다", word: "penetrate" },
  { meaning: "기재, 등록", word: "registration" },
  { meaning: "생산적인, 다산의", word: "productive" },
  { meaning: "관련된, 적절한", word: "relevant" },
  { meaning: "반지름", word: "radius" },
  { meaning: "얽히게 하다,  혼란시키다", word: "tangle" },
  { meaning: "부주의한, 무모한", word: "reckless" },
  { meaning: "이식 유전자의[에 의한]", word: "transgenic" },
  { meaning: "(면밀한) 조사", word: "scrutiny" },
  { meaning: "수의사", word: "veterinarian" },
  { meaning: "<화학> 합성의", word: "synthetic" },
  { meaning: "무게를 달다", word: "weigh" },
  { meaning: "폭로하다,  (비밀)알아내다", word: "uncover" },
  { meaning: "부상, 부상하게 하다", word: "wound" },
];
